### ISSUE TITLE
给作者一个参考吧

### ISSUE THREAD

**Issue by chenxudong2020** [zizifn/edgetunnel#100]
https://github.com/ShadowsocksR-Live/shadowsocksr-native
我一直在想要是能在香港上搞个这个再出门是不是安全多了

**Comment by zizifn** [comment]
> https://github.com/ShadowsocksR-Live/shadowsocksr-native 我一直在想要是能在香港上搞个这个再出门是不是安全多了

我没有发现这个项目在安全上和 v2ray ws + tls 有什么区别。可能是我没有理解。

**Comment by chenxudong2020** [comment]
这个项目相当于 client https访问 建立在香港的一个网站此网站https 大陆通过伪装http访问此网站 然后网站内部转发

> > https://github.com/ShadowsocksR-Live/shadowsocksr-native 我一直在想要是能在香港上搞个这个再出门是不是安全多了
> 
> 我没有发现这个项目在安全上和 v2ray ws + tls 有什么区别。可能是我没有理解。
![image](https://user-images.githubusercontent.com/61214170/218245115-8577db5d-b4f9-43cf-a892-905261a0098f.png)
客户端是标准的 [SOCKS5](https://zh.wikipedia.org/wiki/SOCKS) 服务器, 客户端 与远端 web 服务器 以 HTTPS 协议通讯, 通讯内容是协商升级成 [WebSocket](https://zh.wikipedia.org/wiki/WebSocket) 协议, 协商成功后, 就以 WebSocket 协议进行基于长连接的数据交换, 直到某一方关闭连接.
[WebSocket 简明教程](https://github.com/abbshr/abbshr.github.io/issues/22)

交换的数据可经过 SS/SSR 加密算法处理, 甚至不用加密, 因为经 HTTPS 协议传输的内容, 包括请求路径URL, 数据等, 都是经过强加密的, GFW 破解不了, 即便 GFW 牛逼到真能破解了, 那 HTTPS 协议本身也就该升级换代了.
充当 反向代理 的 web 服务器必须有正式的域名, 有真正的数字证书. 这些可以通过 [freenom.com](https://freenom.com/) 和 [letsencrypt.org](https://letsencrypt.org/) 免费 或 付费 获得, 后续的安装教程有详细讲解.
远端 反向代理 条目 URL 字串必须足够复杂, 足够随机, 以增加 GFW 穷举法猜算出来的难度. 一个随机生成的 UUID 字串就足够 GFW 喝一壶的, 况且我们也可以随时更换.
远端 反向代理 服务器采用市面上常见的 web 服务器软件就可以, 没特殊要求. 这彻底杜绝了 GFW 的被动检测和主动嗅探，因为网站是真实存在的，经得住 GFW 的各种威逼利诱。
与 反向代理 web 服务器进行通讯的 SSRoT 服务器也是基于 WebSocket 协议, 然后它将数据解包后转发到用户试图访问的 目标网站. 在收到 目标网站 的反馈信息以后, 它 将信息进行 加密, 封包后, 以 WebSocket 帧 发送给 反向代理 服务器, 反代 原封不动 地 转发给 SSRoT 客户端.

说白了就是通过建立一个爱国网站 然后ssr客端 与爱国网站之间 使用标准https

**Comment by zizifn** [comment]
> 

其实本项目就是的，全程 https。

**Comment by zizifn** [comment]
其实是可以把ss 实现在deno上的，只不过我不想去扒ss协议栈，因为上了https，具体里面传输的是哪个协议，意义已经不大了。vless简单好实现。

**Comment by wy580477** [comment]
> 说白了就是通过建立一个爱国网站 然后ssr客端 与爱国网站之间 使用标准https

这和v2ray/xray的websocket tls没有任何区别啊，而且还可能缺乏udp over tcp支持。做出来可能是满足ss/ssr爱好者吧。
