### ISSUE TITLE
deno免费版使用不了本项目。

### ISSUE THREAD

**Issue by sojamesss** [zizifn/edgetunnel#109]
由于 deno 更改了政策，所以项目无法使用。。详情请进TG群交流。。
https://deno.com/deploy/docs/pricing-and-limits#tls-proxying

**Comment by zizifn** [comment]
你在说什么？来源？

**Comment by zizifn** [comment]
我看了， log了。。。

**Comment by KENAN1412** [comment]
用不了了吗？

**Comment by zizifn** [comment]
> 用不了了吗？

是的，端口是 443 的网站代理不了啦。http 可以，非 443 网站可以。

**Comment by Alex-xxxxxx** [comment]
有其他办法吗？

**Comment by zizifn** [comment]
> 有其他办法吗？

没有，等CF worker吧或者用render。。。

**Comment by wy580477** [comment]
还能当成中转线路用，落地机用vmess tcp 非443端口就行。用*ray的proxysetting功能和clash的relay功能都可以嵌套代理中转。

**Comment by Alex-xxxxxx** [comment]
> 还能当成中转线路用，落地机用vmess tcp协议就行，vmess自带uot，还解决了udp问题。用*ray的proxysetting功能和clash的relay功能都可以嵌套代理中转。

有教程吗？

**Comment by wy580477** [comment]
> > 还能当成中转线路用，落地机用vmess tcp协议就行，vmess自带uot，还解决了udp问题。用*ray的proxysetting功能和clash的relay功能都可以嵌套代理中转。
> 
> 有教程吗？

Clash里面设置这样一个relay代理组就行了。

```
  - name: "relay-deno"
    type: relay
    proxies:
      - Deno
      - "Another-outbound"
```

**Comment by zizifn** [comment]
> > > 还能当成中转线路用，落地机用vmess tcp协议就行，vmess自带uot，还解决了udp问题。用*ray的proxysetting功能和clash的relay功能都可以嵌套代理中转。
> > 
> > 
> > 有教程吗？
> 
> Clash里面设置这样一个relay代理组就行了。
> 
> ```
>   - name: "relay-deno"
>     type: relay
>     proxies:
>       - Deno
>       - "Another-outbound"
> ```

中转是什么意思? 
本机--> deno vless-->vps vmess?

**Comment by zizifn** [comment]
> > > > > 还能当成中转线路用，落地机用vmess tcp协议就行，vmess自带uot，还解决了udp问题。用*ray的proxysetting功能和clash的relay功能都可以嵌套代理中转。
> > > > 
> > > > 
> > > > 有教程吗？
> > > 
> > > 
> > > Clash里面设置这样一个relay代理组就行了。
> > > ```
> > >   - name: "relay-deno"
> > >     type: relay
> > >     proxies:
> > >       - Deno
> > >       - "Another-outbound"
> > > ```
> > 
> > 
> > 中转是什么意思? 本机--> deno vless-->vps vmess?
> 
> 是的。理论上里面嵌套任何tcp协议都行，本机流量套两次代理协议，deno解开一层把里面的代理协议流量发给落地机。

真会玩，不过加tg群，里面有deno 反代代码。。
