### ISSUE TITLE
好像速度跑上去了内存会boom

### ISSUE THREAD

**Issue by Fangliding** [zizifn/edgetunnel#115]
rt 512m都炸了()
要不考虑docker部署方式不用js实现用sing-box之类的低占用的core 顺便还可以支持vmess()

**Comment by Fangliding** [comment]
![Uploading Screenshot_2023-04-20-13-30-16-565_com.android.chrome.jpg…]()

**Comment by Fangliding** [comment]
![Screenshot_2023-04-20-13-30-16-565_com android chrome](https://user-images.githubusercontent.com/45535409/233342350-0e72faff-ed85-4fab-af41-ee9f94c2e760.jpg)

**Comment by zizifn** [comment]
卧槽牛逼啊，我的确没有写 back pressure  逻辑。能告知做了什么吗？改天我改下 code。 vmess 太麻烦了，可以实现但是很费时间。

**Comment by zizifn** [comment]
你是并发请求了吗？

**Comment by Fangliding** [comment]
> 你是并发请求了吗？

并没有 我到一台vps上装了一个v2raya挂上节点想测试一下render的极限速度 测试方法是通过http代理 wget下载cf的一个测速文件 所以是单线程 然后大概跑到20MB/s的样子(这个时候的hax的cpu扛不住了) 跑了一会跑个几百MB或者一个多G连接会断开 就这样反反复复试了几次我发现连不上了 打开render就这样了

**Comment by zizifn** [comment]
> > 你是并发请求了吗？
> 
> 并没有 我到一台vps上装了一个v2raya挂上节点想测试一下render的极限速度 测试方法是通过http代理 wget下载cf的一个测速文件 所以是单线程 然后大概跑到20MB/s的样子(这个时候的hax的cpu扛不住了) 跑了一会跑个几百MB或者一个多G连接会断开 就这样反反复复试了几次我发现连不上了 打开render就这样了

谢谢，我知道了。我会在 cf worker 版本 尽量修复这种问题，到时候你在测试。

**Comment by Fangliding** [comment]
> > > 你是并发请求了吗？
> > 
> > 
> > 并没有 我到一台vps上装了一个v2raya挂上节点想测试一下render的极限速度 测试方法是通过http代理 wget下载cf的一个测速文件 所以是单线程 然后大概跑到20MB/s的样子(这个时候的hax的cpu扛不住了) 跑了一会跑个几百MB或者一个多G连接会断开 就这样反反复复试了几次我发现连不上了 打开render就这样了
> 
> 谢谢，我知道了。我会在 cf worker 版本 尽量修复这种问题，到时候你在测试。另外 cf 的测试文件多大?

wget "http://speed.cloudflare.com/__down?byt
es=1145141919810" -O /dev/null 大小改byte自选 但是填个超级巨大的数好像下到9.几G会直接fail

**Comment by zizifn** [comment]
> > > > 你是并发请求了吗？
> > > 
> > > 
> > > 并没有 我到一台vps上装了一个v2raya挂上节点想测试一下render的极限速度 测试方法是通过http代理 wget下载cf的一个测速文件 所以是单线程 然后大概跑到20MB/s的样子(这个时候的hax的cpu扛不住了) 跑了一会跑个几百MB或者一个多G连接会断开 就这样反反复复试了几次我发现连不上了 打开render就这样了
> > 
> > 
> > 谢谢，我知道了。我会在 cf worker 版本 尽量修复这种问题，到时候你在测试。另外 cf 的测试文件多大?
> 
> wget "http://speed.cloudflare.com/__down?bytes=1145141919810" -O /dev/null 大小改byte自选 最大10000000000 高于这个数也会直接在这个数停下来 大约9.31GB 也可以用这玩意刷流量 搞个webenchmark就行了

你干爆过原版 v2ray 吗？

**Comment by zizifn** [comment]
> > > > > > 你是并发请求了吗？
> > > > > 
> > > > > 
> > > > > 并没有 我到一台vps上装了一个v2raya挂上节点想测试一下render的极限速度 测试方法是通过http代理 wget下载cf的一个测速文件 所以是单线程 然后大概跑到20MB/s的样子(这个时候的hax的cpu扛不住了) 跑了一会跑个几百MB或者一个多G连接会断开 就这样反反复复试了几次我发现连不上了 打开render就这样了
> > > > 
> > > > 
> > > > 谢谢，我知道了。我会在 cf worker 版本 尽量修复这种问题，到时候你在测试。另外 cf 的测试文件多大?
> > > 
> > > 
> > > wget "http://speed.cloudflare.com/__down?bytes=1145141919810" -O /dev/null 大小改byte自选 最大10000000000 高于这个数也会直接在这个数停下来 大约9.31GB 也可以用这玩意刷流量 搞个webenchmark就行了
> > 
> > 
> > 你干爆过原版 v2ray 吗？
> 
> 除了xray的wireguard出站有一点问题我从没见过v2ray爆炸的 512m还是docker环境没别的杂七杂八的东西更不可能() 硬干的话 理论上极限负载下cpu比内存先寄

你等我这周末，粗暴优化一把。你喜欢的话，可以tg群，不喜欢，我周末加好，这里通知你。

**Comment by zizifn** [comment]
fixed in https://github.com/zizifn/edgetunnel/commit/9aa1b0573fedfd359634d1cb95cbed1951b07f91#diff-c3d56c72007050c8340ea91531b760aac80fbe6596db9b66f4aa7ce6f2dbc248
