### ISSUE TITLE
Maybe a way to bypass the render ban

### ISSUE THREAD

**Issue by lsadls** [zizifn/edgetunnel#116]
About 1 year ago I tried to deploy v2ray on render but they result instant account ban, then I discovered that if any text files contains keywords like "v2ray" "vless" etc render will ban the account, then I use base64 to encode the config file and decode it when deploying and it successfully bypass the ban.

So my guess is that render will first check all text files for keywords then if no match, start the deployment and never check twice.

I think by use an alt account and crate a new repo that only contains necessary files with no keyword related to "v2ray", this project may bypass the ban.

Unfortunately I'm a little busy right now so I can't test it myself, anyone who has interest with can do test.

**Comment by zizifn** [comment]
cf worker working very good, close this one..
