### ISSUE TITLE
为什么代码里面，加了delay？

### ISSUE THREAD

**Issue by BanKnight** [zizifn/edgetunnel#117]
```typescript
await remoteConnection.readable.pipeTo(new WritableStream({
            start () {
                if (webSocket.readyState === webSocket.OPEN) {
                    webSocket.send(vlessResponseHeader);
                }
            },
            async write (chunk, controller) {
                function send2WebSocket() {
                    if (webSocket.readyState !== webSocket.OPEN) {
                        controller.error(`can't accept data from remoteConnection!.readable when client webSocket is close early`);
                        return;
                    }
                    webSocket.send(chunk);
                }
                remoteChunkCount++;
                if (remoteChunkCount < 20) {
                    send2WebSocket();
                } else if (remoteChunkCount < 120) {
                    await delay1(10);               //这里加了延迟
                    send2WebSocket();
                } else if (remoteChunkCount < 500) {
                    await delay1(20);     //这里加了延迟
                    send2WebSocket();
                } else {
                    await delay1(50);   //这里加了延迟
                    send2WebSocket();
                }
            },
            close () {
                console.log(`[${address}:${portWithRandomLog}] remoteConnection!.readable is close`);
            },
            abort (reason) {
                closeWebSocket(webSocket);
                console.error(`[${address}:${portWithRandomLog}] remoteConnection!.readable abort`, reason);
            }
        }));
```

看起来是故意的，但是这样一来，吞吐不就慢了吗？
并且，大量数据传送的时候，会导致堆积数据，内存上涨

**Comment by zizifn** [comment]
因为 之前 deno ws 有这个issue https://github.com/denoland/deno/issues/17332。

一旦下载大文件的文件，就丢消息（https://github.com/zizifn/edgetunnel/issues/87），所以故意限制发包。。内存不会涨的。因为这是流，如果发包太慢，会自动降低上游（比如youtube）的下载速度的。

**Comment by BanKnight** [comment]
我看了一下，说是这个问题已经没了，所以可以考虑删掉了。
再就是，不如改成nodejs吧，至少这方面没啥问题。

**Comment by zizifn** [comment]
> 我看了一下，说是这个问题已经没了，所以可以考虑删掉了。 再就是，不如改成nodejs吧，至少这方面没啥问题。

项目有 nodejs 版本。没有这个逻辑。

**Comment by BanKnight** [comment]
内存涨的问题，你说的这个是tcp的流控，但实际上，这是底层接收数据层面的控制，而它是大于业务层的速度的。
你在这里增加了一定时间的延迟，会导致额外增加数据的滞留时间。

这里的write函数调用，我不知道在deno中，上层是否通过await调用，如果是通过await调用，那有可能会带来一个逐渐增加的延迟（不过这种概率比较低，毕竟没有这样的issue）。

我看另外一个issue，发送大文件时候导致的内存涨，有可能这里也是部分原因。

nodejs 版本是哪个文件？我想去看看，刚找了一下，发现没有找到。

**Comment by zizifn** [comment]
> 内存涨的问题，你说的这个是tcp的流控，但实际上，这是底层接收数据层面的控制，而它是大于业务层的速度的。 你在这里增加了一定时间的延迟，会导致额外增加数据的滞留时间。
> 
> 这里的write函数调用，我不知道在deno中，上层是否通过await调用，如果是通过await调用，那有可能会带来一个逐渐增加的延迟（不过这种概率比较低，毕竟没有这样的issue）。
> 
> 我看另外一个issue，发送大文件时候导致的内存涨，有可能这里也是部分原因。
> 
> nodejs 版本是哪个文件？我想去看看，刚找了一下，发现没有找到。

https://github.com/zizifn/edgetunnel/blob/main/apps/node-vless/src/main.ts

关于内存问题，我一会再回复你。

**Comment by zizifn** [comment]
> 内存涨的问题，你说的这个是tcp的流控，但实际上，这是底层接收数据层面的控制，而它是大于业务层的速度的。 你在这里增加了一定时间的延迟，会导致额外增加数据的滞留时间。
> 
> 这里的write函数调用，我不知道在deno中，上层是否通过await调用，如果是通过await调用，那有可能会带来一个逐渐增加的延迟（不过这种概率比较低，毕竟没有这样的issue）。
> 
> 我看另外一个issue，发送大文件时候导致的内存涨，有可能这里也是部分原因。
> 
> nodejs 版本是哪个文件？我想去看看，刚找了一下，发现没有找到。

1. 假设通过代理访问 youtube
2. 客户端使用 websocket 连接 Deno/nodejs
3. Deno/nodejs server 会对 youtube， 创建是一个tcp 连接 （upstream）。
4. 这里我把 upstream socket 转成了 web `ReadableStream` 
5. 然是使用 pipe 到一个 `WritableStream`, write 方法
    It can return a promise to signal the success or failure of the write operation. This method will be called only after previous writes 
    have succeeded,
6. 这样会导致 upstream ReadableStream 的 内部 queue 是满的，从而使得 内部调用 upstream socket pause read，触发 tcp 流控。

所以会增加内存，但是不会很多，因为 取决于 socket buffer 的设置。

**Comment by BanKnight** [comment]
> it can return a promise to signal the success or failure of the write operation. This method will be called only after previous writes
have succeeded

这个的出处是哪？我在nodejs.org上面没找到，我只找到了_write函数的说明：
[https://nodejs.org/dist/latest-v20.x/docs/api/stream.html#writable_writechunk-encoding-callback
](https://nodejs.org/dist/latest-v20.x/docs/api/stream.html#writable_writechunk-encoding-callback)

但也没有提到write的类似问题。
nodejs 粗略看了一下，比deno完善的感觉。

**Comment by zizifn** [comment]
> > it can return a promise to signal the success or failure of the write operation. This method will be called only after previous writes
> > have succeeded
> 
> 这个的出处是哪？我在nodejs.org上面没找到，我只找到了_write函数的说明： [https://nodejs.org/dist/latest-v20.x/docs/api/stream.html#writable_writechunk-encoding-callback ](https://nodejs.org/dist/latest-v20.x/docs/api/stream.html#writable_writechunk-encoding-callback)
> 
> 但也没有提到write的类似问题。 nodejs 粗略看了一下，比deno完善的感觉。

我为了尽量用 web standard，所以我采用的是是 web stream。。。
https://developer.mozilla.org/en-US/docs/Web/API/WritableStream/WritableStream
https://nodejs.org/dist/latest-v20.x/docs/api/webstreams.html#new-writablestreamunderlyingsink-strategy
