### ISSUE TITLE
Will be assigned a different IP every second

### ISSUE THREAD

**Issue by NabiKAZ** [zizifn/edgetunnel#126]
You should note that this method will be assigned a different IP every second. This is not suitable for sensitive things.
Proof:
https://twitter.com/nabikaz/status/1659619289865830409

**Comment by zizifn** [comment]
> You should note that this method will be assigned a different IP every second. This is not suitable for sensitive things. Proof: https://twitter.com/nabikaz/status/1659619289865830409

yeah. nothing I can do....
