### ISSUE TITLE
新版js好像访问ip.sb好像没有ipv6

### ISSUE THREAD

**Issue by 759071793** [zizifn/edgetunnel#129]
新版js好像访问ip.sb好像没有ipv6,请问可以增加ipv6支持吗

**Comment by zizifn** [comment]
> 新版js好像访问ip.sb好像没有ipv6,请问可以增加ipv6支持吗

ip.sb 是 cf 托管网站。目前仅仅支持 ipv4

**Comment by 759071793** [comment]
新版js已经支持，感谢作者fix
