### ISSUE TITLE
新版部署后提示报错

### ISSUE THREAD

**Issue by jiangbeth** [zizifn/edgetunnel#156]
{"clientTcpRtt":1,"longitude":"-87.61330","latitude":"41.87640","tlsCipher":"ECDHE-ECDSA-AES128-GCM-SHA256","continent":"NA","asn":132892,"clientAcceptEncoding":"gzip","country":"US","tlsClientAuth":{"certIssuerDNLegacy":"","certIssuerSKI":"","certSubjectDNRFC2253":"","certSubjectDNLegacy":"","certFingerprintSHA256":"","certNotBefore":"","certSKI":"","certSerial":"","certIssuerDN":"","certVerified":"NONE","certNotAfter":"","certSubjectDN":"","certPresented":"0","certRevoked":"0","certIssuerSerial":"","certIssuerDNRFC2253":"","certFingerprintSHA1":""},"tlsExportedAuthenticator":{"clientFinished":"375b2a0a4c480ff577060648d13dadedfcc3d5de7ec61dbb0fc9e789544fb7ed","clientHandshake":"0b8bb59c6b822cd866ea7d14a881215d690dd43b214f8abc4f9c36d3ff1debee","serverHandshake":"58f6278ad7d7524c2056c26cdf459f9227b369c5de9e999e032751d573313afd","serverFinished":"6546492d947d8d68a72bec169feb0cd6fa66f089961110b17b4a624d3a3a5733"},"tlsVersion":"TLSv1.2","colo":"SIN","timezone":"America/Chicago","region":"Illinois","requestPriority":"","httpProtocol":"HTTP/1.1","regionCode":"IL","asOrganization":"Cloudflare","edgeRequestKeepAliveStatus":1,"botManagement":{"corporateProxy":false,"verifiedBot":false,"jsDetection":{"passed":false},"staticResource":false,"detectionIds":{},"score":99}}

**Comment by zizifn** [comment]
里面有 IP 相关信息，删除了。相信你没有问题了。

**Comment by jiangbeth** [comment]
谢谢大佬，百忙回复/
