### ISSUE TITLE
picture not found 

### ISSUE THREAD

**Issue by Glimpser-zz** [zizifn/edgetunnel#159]
hi 

in this link 
https://github.com/zizifn/edgetunnel/blob/download_file/doc/edge-tunnel-deno.md
please fix these links 

https://raw.githubusercontent.com/zizifn/edgetunnel/main/doc/deno-deploy.gif
https://raw.githubusercontent.com/zizifn/edgetunnel/main/doc/deno-deploy2.gif

or add text to how  to config 

thanks .

**Comment by zizifn** [comment]
I deleted them, please check others repo https://github.com/edgetunnel/edgetunnel
