### ISSUE TITLE
新版打不开一些CF网站

### ISSUE THREAD

**Issue by kumikooumae** [zizifn/edgetunnel#162]
https://whoer.net/cdn-cgi/trace
https://www.visa.cn/cdn-cgi/trace

**Comment by zizifn** [comment]
shortly 会有一般比较完美的方案。等几天哈

**Comment by zizifn** [comment]
好用了，试试看？？注意配置好你的proxyip

**Comment by zizifn** [comment]
> 用最新版的worker-vless.js文件测试了下面两个网站，无论是let proxyIP = '';或let proxyIP = '114.114.114.114';情况都一样, 但其他能够访问的网站同样是设置上面两种情况也是能够正常访问，感觉let proxyIP这个参数设置与否没有关系 而下面两个网站使用xray或v2ray_simple配置的vless over ws over TLS（没有vision，没有REALITY）却能够正常访问
> 
> https://whoer.net https://www.whatismyip.com
> 
> chrome浏览器报告：
> 
> 无法访问此网站www.whatismyip.com 意外终止了连接。
> 
> 无法访问此网站whoer.net 意外终止了连接
> 
> firefox浏览器报告：
> 
> 建立安全连接失败
> 
> 连接到 [www.whatismyip.com](http://www.whatismyip.com) 时发生错误。PR_END_OF_FILE_ERROR
> 
> 错误代码：PR_END_OF_FILE_ERROR
> 
> 建立安全连接失败
> 
> 连接到 whoer.net 时发生错误。PR_END_OF_FILE_ERROR
> 
> 错误代码：PR_END_OF_FILE_ERROR
你当然不能用114.114.114.114 了。

**Comment by zizifn** [comment]
> 我试了一些境内的住宅ip地址和美国的住宅ip地址（173.198.248.39）填到let proxyIP后面，但情况是一样的，那这个中转ip是什么作用呢？是另外一个代理ip地址吗？

有一些神奇的 ip，可以无条件转发所有 cf 的流量。我无法提供给你这些 IP，你可以加群问其他人。

**Comment by zizifn** [comment]
最新版应该在配置好IP 情况下，算是很完整了。关闭 issue。。

**Comment by wutongskype** [comment]
> proxyip

大佬群名叫啥??给个传送门.

**Comment by zizifn** [comment]
> > proxyip
> 
> 大佬群名叫啥??给个传送门.

你去这里吧。https://t.me/cf_push

**Comment by zizifn** [comment]
> 

https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#considerations

**Comment by zizifn** [comment]
> @zizifn 谢大大带路！ 终于完全搞清楚CF中转ip是什么意思了，怪不得那么多香港跑路云，乐此不疲的 不过话说回来，这种方式还是有安全风险，你这边是否考虑向CF的技术社区提出CF workers修复不能访问CF托管网站这个bug

https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#considerations

**Comment by Su-yj** [comment]
> > @zizifn 谢大大带路！ 终于完全搞清楚CF中转ip是什么意思了，怪不得那么多香港跑路云，乐此不疲的 不过话说回来，这种方式还是有安全风险，你这边是否考虑向CF的技术社区提出CF workers修复不能访问CF托管网站这个bug
> 
> 已经反馈了，这是反馈后的文档更新。。https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#considerations

官方有说什么时候会修复吗？😂一直在等待这个出来

**Comment by upsangel** [comment]
> 按照cloudflare刚刚的更新 https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#considerations
> 
> 是否使用fetch应该就可以呢？
> 
> proxy request failed, cannot connect to the specified address
> 
> Your socket is connecting to an address that was disallowed. Examples of a disallowed address include Cloudflare IPs, localhost, and private network IPs.
> 
> If you need to connect to addresses on port 80 or 443 to make HTTP requests, use fetch.

我也不是太懂，但從z大代碼分析，fetch似乎只是處理直接訪問你的worker，以及訪問worker/uuid時候，如果是其他情況，則會觸發vlessOverWSHandler(request) 來處理。後者是進行VLESS TCP轉發。你的意思是把VLESS 轉發打包成fecth射出去嗎？這個想法可行嗎？聽上去怪怪的

**Comment by zizifn** [comment]
不可以fetch 拿不到 tls 握手包，tls 握手包需要传给客户的。

**Comment by Lonor** [comment]
都大半年了，还没有 re-enable...

**Comment by WorldlineChanger** [comment]
官方修复遥遥无期

**Comment by zqs78** [comment]
@zizifn 大佬，为了更加安全，请问如何自己搭建proxy ip？找不到教程

**Comment by cloudeye2** [comment]
官方的此限制是为了防止在worker中通过代码实现企业版才有的Page Rules高级功能。
不做限制的话，理论上可以在page前套一层worker代理，实现任何Page Rules。

**Comment by la3rence** [comment]
> 官方的此限制是为了防止在worker中通过代码实现企业版才有的Page Rules高级功能。
> 
> 不做限制的话，理论上可以在page前套一层worker代理，实现任何Page Rules。
> 
> 

不一定…… Page Rules 这种功能压根没啥值得用的， 前后端自身都可以实现；另外就算是付费用户也无法在 Worker 中进行 outbound cf 网络。

我之前猜测的真实原因是防止用户滥用大量免费账号/免费 Workers 对 cf 自身内部站点做 CC 攻击，甚至更大规模的 DDoS —— 相当于零成本借 cf 的左手打 cf 自己的右手。😅

**Comment by dong615** [comment]
> > > proxyip
> > 
> > 
> > 大佬群名叫啥??给个传送门.
> 
> 你去这里吧。https://t.me/cf_push

这个每天提供很多，我随便填了一组进去，没用啊

**Comment by rain7777777** [comment]
> @zizifn 谢大大带路！ 终于完全搞清楚CF中转ip是什么意思了，怪不得那么多香港跑路云，乐此不疲的 不过话说回来，这种方式还是有安全风险，你这边是否考虑向CF的技术社区提出CF workers修复不能访问CF托管网站这个bug

请问这是什么意思，我也是输入提供的ip,没用
