### ISSUE TITLE
使用Pages部署，点部署按钮不起作用

### ISSUE THREAD

**Issue by gaboolic** [zizifn/edgetunnel#168]
开控制台看cf有报错
<img width="621" alt="image" src="https://github.com/zizifn/edgetunnel/assets/3831173/8bb9b75a-e521-41c1-b1eb-77d3b4d891a4">
这是为啥呢

**Comment by zizifn** [comment]
啊，pages 暂时没有办法无痛部署。我没写啊

**Comment by jaydong2016** [comment]
> 啊，pages 暂时没有办法无痛部署。我没写啊

有人出视频直接用你的 js 在 pages 部署，可以用

**Comment by zizifn** [comment]
> > 啊，pages 暂时没有办法无痛部署。我没写啊
> 
> 有人出视频直接用你的 js 在 pages 部署，可以用

那我就不知道为什么了....

**Comment by gaboolic** [comment]
貌似是cf那会挂了。现在又可以了

**Comment by gaboolic** [comment]
> 啊，pages 暂时没有办法无痛部署。我没写啊

https://edgetunnel.github.io/  我看的这个，是你的不？现在也打不开了

**Comment by gaboolic** [comment]
好像是这个项目https://github.com/edgetunnel/edgetunnel

**Comment by gaboolic** [comment]
文档上写的Fork edgetunnel 本项目
https://github.com/zizifn/edgetunnel
我也搞不懂该fork哪个了，貌似代码不一样

**Comment by gaboolic** [comment]
现在pages能创建了，有个新问题是build失败
按文档上写的用npm run cf-page-vless
然后报错npm ERR! Missing script: "cf-page-vless"
我看了一下，确实没有cf-page-vless 这是怎么回事

**Comment by gaboolic** [comment]
我看目前最新的代码是
"scripts": {
    "deploy": "wrangler deploy",
    "dev-vless": "wrangler dev src/worker-vless.js"
  }
所以该用哪一个呢

**Comment by gaboolic** [comment]
> > 啊，pages 暂时没有办法无痛部署。我没写啊
> 
> 有人出视频直接用你的 js 在 pages 部署，可以用


这个我还真没看到，我是听朋友说了一个项目名 在github上搜的
