### ISSUE TITLE
Some websites keep returning empty response.

### ISSUE THREAD

**Issue by torxxxx** [zizifn/edgetunnel#169]
I have tested several websites such as :
1.1.1.1
speedtest.net
ipaddress.my
whatismyip.com
through the cloudflare worker service with  vless-worker.js ,the commit serial of which is e77abfc, deployed on it.
BUT all of them keep returning nothing.
Google.com Youtube.com Duckduckgo.com, etc works fine.

**Comment by zizifn** [comment]
you need cf bug https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#considerations.. you need to find some kind of proxy ip and add it here https://github.com/zizifn/edgetunnel/blob/main/src/worker-vless.js#L9
