### ISSUE TITLE
Request to Add VLESS Encryption and VMess Protocol Support

### ISSUE THREAD

**Issue by amin1softco** [zizifn/edgetunnel#171]
I hope this message finds you well. I am writing to request the addition of VLESS encryption and VMess protocol support to an existing file. I believe this enhancement would greatly improve the functionality and security of the application.

VLESS (Versatile Encryption Socks Tunnel) is a newer and more secure protocol that is designed to provide enhanced encryption and protection for network traffic. By implementing VLESS encryption, we can ensure that the data transmitted between clients and servers remains confidential and protected against potential threats.

In addition to VLESS, I would also like to propose the inclusion of VMess protocol support

I strongly believe that by incorporating VLESS encryption and VMess protocol support, we can significantly enhance the security and performance of the this project.

Thank you for considering this request. I look forward to your positive response and the possibility of incorporating these improvements into the project.

**Comment by zizifn** [comment]
same as #158
