### ISSUE TITLE
问题请在这里comment, 建议新开issue

### ISSUE THREAD

**Issue by zizifn** [zizifn/edgetunnel#18]
如上。。。。

**Comment by conancheng** [comment]
部署成功后主的可以连的上，环境里的备用的死活连接不上。。。。实在搞不懂这个逻辑啊 难道cloudflare我还需要重新注册一个账号才行？

**Comment by zizifn** [comment]
> 部署成功后主的可以连的上，环境里的备用的死活连接不上。。。。实在搞不懂这个逻辑啊 难道cloudflare我还需要重新注册一个账号才行？ ![image](https://user-images.githubusercontent.com/24214834/165238374-934df3c8-75c9-4387-b171-9f62fb74300e.png) ![image](https://user-images.githubusercontent.com/24214834/165239410-bf938bb4-47b9-4a97-aacb-aa92502dec1f.png) 看heroku的部署状态也是成功的

一般需要确保，***.herokuapp.com 能够返回 Bad Request, 如果不能返回，就需要看看 是什么错误。。
![image](https://user-images.githubusercontent.com/1803942/165239810-9e1bfc3e-9c4f-49e4-b74a-0cac44187149.png)

**Comment by conancheng** [comment]
![image](https://user-images.githubusercontent.com/24214834/165246195-c80ed6b0-32ed-45ba-9f46-4bca4c51504d.png)
OK 正常了。。。可能启动需要时间。。。我啥也没动

**Comment by conancheng** [comment]
> > ![image](https://user-images.githubusercontent.com/24214834/165246195-c80ed6b0-32ed-45ba-9f46-4bca4c51504d.png) OK 正常了。。。可能启动需要时间。。。我啥也没动
> 
> 只是友善提醒，你的图片有你的 email 地址。。 注意不要泄露 自己app 名字。。。尽量起个特别的，然后配置在 github secret里面。。

好的 谢谢提醒 还有个问题 这两个主备怎么实现在手机端自动切换。。。我看了下V2RAYNG肯定是不行 要手动点下

**Comment by zizifn** [comment]
> > > ![image](https://user-images.githubusercontent.com/24214834/165246195-c80ed6b0-32ed-45ba-9f46-4bca4c51504d.png) OK 正常了。。。可能启动需要时间。。。我啥也没动
> > 
> > 
> > 只是友善提醒，你的图片有你的 email 地址。。 注意不要泄露 自己app 名字。。。尽量起个特别的，然后配置在 github secret里面。。
> 
> 好的 谢谢提醒 还有个问题 这两个主备怎么实现在手机端自动切换。。。我看了下V2RAYNG肯定是不行 要手动点下

这个我就不知道了。。貌似有人在 worker 中写逻辑。。但是个人建议自己手动切换。。另外，heroku app 会休眠，休眠不计入小时，然后有访问就会自动恢复。

**Comment by conancheng** [comment]
> 

大概理解了 也就是你不是24小时用的话一般一个月是够用的了

**Comment by zizifn** [comment]
> > 
> 
> 大概理解了 也就是你不是24小时用的话一般一个月是够用的了

是的。

**Comment by zmr-lucidlynx** [comment]
![image](https://user-images.githubusercontent.com/25640103/165267603-64aaaaa7-85fd-4a52-973b-244ef906217c.png)
请问在cloudflare出现这个问题是什么原因

**Comment by zmr-lucidlynx** [comment]
> > ![image](https://user-images.githubusercontent.com/25640103/165267603-64aaaaa7-85fd-4a52-973b-244ef906217c.png) 请问在cloudflare出现这个问题是什么原因
> 
> cloudflare woker? 还是 cloudflare tunnel?

cloudflare woker

**Comment by zizifn** [comment]
> > > ![image](https://user-images.githubusercontent.com/25640103/165267603-64aaaaa7-85fd-4a52-973b-244ef906217c.png) 请问在cloudflare出现这个问题是什么原因
> > 
> > 
> > cloudflare woker? 还是 cloudflare tunnel?
> 
> cloudflare woker
这是正常的，你直接用http访问就是这个错误，你用客户端，就应该没有问题。。

**Comment by zmr-lucidlynx** [comment]
> 是直接用V2ray客户端访问么，我复制这个链接进去V2，发现用不了

**Comment by zizifn** [comment]
> > 是直接用V2ray客户端访问么，我复制这个链接进去V2，发现用不了

直接用客户端访问 heroku 好用吗？请查看readme 最后的 https://github.com/zizifn/v2ray-heroku#v2rayn， 请确保不要输入错内容。 UUID

**Comment by zmr-lucidlynx** [comment]
> > > 是直接用V2ray客户端访问么，我复制这个链接进去V2，发现用不了
> 
> 直接用客户端访问 heroku 好用吗？请查看readme 最后的 [https://github.com/zizifn/v2ray-heroku#v2rayn，](https://github.com/zizifn/v2ray-heroku#v2rayn%EF%BC%8C) 请确保不要输入错内容。 UUID

直接访问Heroku也不行 不知道是不是我用的校园网的问题。

**Comment by zizifn** [comment]
> > > > 是直接用V2ray客户端访问么，我复制这个链接进去V2，发现用不了
> > 
> > 
> > 直接用客户端访问 heroku 好用吗？请查看readme 最后的 [https://github.com/zizifn/v2ray-heroku#v2rayn，](https://github.com/zizifn/v2ray-heroku#v2rayn%EF%BC%8C) 请确保不要输入错内容。 UUID
> 
> 直接访问Heroku也不行 不知道是不是我用的校园网的问题。

手机网络试试呀。

**Comment by zhaoguomanong** [comment]
可以加个首页伪装吗？ 比如访问/ 路径打开一个伪装网页，另外一个特定的路径再去v2ray。 可以提供下思路吗？这个heroku上不知道怎么用nginx分流。 谢谢！

**Comment by zizifn** [comment]
> 可以加个首页伪装吗？ 比如访问/ 路径打开一个伪装网页，另外一个特定的路径再去v2ray。 可以提供下思路吗？这个heroku上不知道怎么用nginx分流。 谢谢！
> 
> 刚找了个例子 https://github.com/Lbingyi/HerokuV2ray ，正在研究中....
> 
> 不知道加了首页伪装有没有作用， heroku会定期查看应用首页吗？

1. 首先，我不会在这个repo 下实现这种功能，我得目的是尽量保持直接使用官方得 images `v2fly/v2fly-core:latest` ， 保持简洁，部署速度也会快。另外这样v2fly做了什么变动，我这里在重现跑下action就可以得到最新版。因为v2fly 会维护他们得docker image.

3. 实现起来也很简单，你可以去其他人得项目上参考下

ps 个人感觉，首页伪装是伪需求。因为v2ray 本身就会返回首页，只不过是bad request 字样。

**Comment by zizifn** [comment]
> 可以加个首页伪装吗？ 比如访问/ 路径打开一个伪装网页，另外一个特定的路径再去v2ray。 可以提供下思路吗？这个heroku上不知道怎么用nginx分流。 谢谢！
> 
> 刚找了个例子 https://github.com/Lbingyi/HerokuV2ray ，正在研究中....
> 
> 不知道加了首页伪装有没有作用， heroku会定期查看应用首页吗？

另外，老老实实**个人**使用，保证自己地址合uuid不要泄露，我都用了两年，没有见 heroku，停止我的应用。

**Comment by zhaoguomanong** [comment]
> > 可以加个首页伪装吗？ 比如访问/ 路径打开一个伪装网页，另外一个特定的路径再去v2ray。 可以提供下思路吗？这个heroku上不知道怎么用nginx分流。 谢谢！
> > 刚找了个例子 https://github.com/Lbingyi/HerokuV2ray ，正在研究中....
> > 不知道加了首页伪装有没有作用， heroku会定期查看应用首页吗？
> 
> 另外，老老实实**个人**使用，保证自己地址合uuid不要泄露，我都用了两年，没有见 heroku，停止我的应用。

好的，那我就放心了。 谢谢

**Comment by abluns** [comment]
最惨的莫过于，一直deploy后发现heroku的不能访问，套了tunnel也无法访问，折腾了一天，原来发现不止worker的域名被墙，我优选的CF IP也被墙了。起码build了9次以上，折腾了一个下午了，换了个CF  IP解决问题。人才了

**Comment by zizifn** [comment]
> 最惨的莫过于，一直deploy后发现heroku自带的地址在v2rayN里设置后不能访问，套了tunnel也无法访问，折腾了一天，原来发现不止CF worker.dev的域名被墙，我优选的CF IP很巧也被墙了，herokuapp.com的二级域名在v2rayN也无法起作用，虽然WEB直接是可以访问的。起码build了9次以上，折腾了一个下午了，换了个CF IP解决问题。人才了

为什么 heroku app 自带URL 不好用？ 应该是好用的。你看下我的图片的V2rayN的设置。

**Comment by abluns** [comment]
> > 最惨的莫过于，一直deploy后发现heroku自带的地址在v2rayN里设置后不能访问，套了tunnel也无法访问，折腾了一天，原来发现不止CF worker.dev的域名被墙，我优选的CF IP很巧也被墙了，herokuapp.com的二级域名在v2rayN也无法起作用，虽然WEB直接是可以访问的。起码build了9次以上，折腾了一个下午了，换了个CF IP解决问题。人才了
> 
> 为什么 heroku app 自带URL 不好用？ 应该是好用的。你看下我的图片的V2rayN的设置。

搞定了，我们两个V2rayN的版本不一样，我昨天看岔了。别名，地址，伪装域名填错了。不过我现在用了CF Tunnels很好。另外用宝塔添加了定时访问herokuapp二级域名的计划，目前很稳。题外话问下那个CF Tunnels虽然是免费计划，我用的是Paypal付款的，如果我在PP里关闭它的循环付款不知道Tunnels会不会被关停。

**Comment by zhaoguomanong** [comment]
请问一下cf tunnels 是不是没有像workers的10万条请求每天的限制？ 
还有就是，tunnels是不是没办法像workers里面写规则按照日期多个heroku帐号轮流用吗？

**Comment by conancheng** [comment]
> 请问一下cf tunnels 是不是没有像workers的10万条请求每天的限制？ 
> 还有就是，tunnels是不是没办法像workers里面写规则按照日期多个heroku帐号轮流用吗？

使用Cloudflare的Workers来中转流量，单双日轮换反代代码(推荐)
const SingleDay = 'app1.herokuapp.com'
const DoubleDay = 'app2.herokuapp.com'
addEventListener(
    "fetch",event => {
    
        let nd = new Date();
        if (nd.getDate()%2) {
            host = SingleDay
        } else {
            host = DoubleDay
        }
        
        let url=new URL(event.request.url);
        url.hostname=host;
        let request=new Request(url,event.request);
        event. respondWith(
            fetch(request)
        )
    }
)

**Comment by zizifn** [comment]
> > > 最惨的莫过于，一直deploy后发现heroku自带的地址在v2rayN里设置后不能访问，套了tunnel也无法访问，折腾了一天，原来发现不止CF worker.dev的域名被墙，我优选的CF IP很巧也被墙了，herokuapp.com的二级域名在v2rayN也无法起作用，虽然WEB直接是可以访问的。起码build了9次以上，折腾了一个下午了，换了个CF IP解决问题。人才了
> > 
> > 
> > 为什么 heroku app 自带URL 不好用？ 应该是好用的。你看下我的图片的V2rayN的设置。
> 
> 搞定了，我们两个V2rayN的版本不一样，我昨天看岔了。别名，地址，伪装域名填错了。不过我现在用了CF Tunnels很好。另外用宝塔添加了定时访问herokuapp二级域名的计划，目前很稳。题外话问下那个CF Tunnels虽然是免费计划，我用的是Paypal付款的，如果我在PP里关闭它的循环付款不知道Tunnels会不会被关停。

不会。另外你只要不手动升级自己plan，就不会收费。具体在setting-->account 查看。
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1803942/167892530-74ae6046-2c78-4332-9d2c-d181b45146a5.png">

**Comment by zhaoguomanong** [comment]
> > 请问一下cf tunnels 是不是没有像workers的10万条请求每天的限制？ 还有就是，tunnels是不是没办法像workers里面写规则按照日期多个heroku帐号轮流用吗？
> 
> 没有10w限制。。j我不知道怎么写规则轮询。。但是应该可以，你可以写个代码动态更新tunnel的Service。。。

代码运行在哪里呢？ 写定时任务去更新tunnel 的 service吗？

**Comment by abluns** [comment]
最新测试结果，本地DNS119.29.29.29浏览器已经无法访问打开*.herokuapp.com的域名了。扶梯后才能打开。

**Comment by LimitBreaker01** [comment]
你好，我想问下我自己之前也是用别人的github项目搭建了heroku节点，以前跑的时候油管可以跑6万速度。后来就莫名速度下降。自己换机场节点还是可以跑6万，但是heroku节点一直就是上不去速度。当初搭建的时候为了提高速度使用了cf反代和自选ip。
最近我看你使用cloudflare tunnel 添加到heroku上，请问效果好吗？还是一般。我的是南方移动宽带100M。

**Comment by zizifn** [comment]
> 你好，我想问下我自己之前也是用别人的github项目搭建了heroku节点，以前跑的时候油管可以跑6万速度。后来就莫名速度下降。自己换机场节点还是可以跑6万，但是heroku节点一直就是上不去速度。当初搭建的时候为了提高速度使用了cf反代和自选ip。 最近我看你使用cloudflare tunnel 添加到heroku上，请问效果好吗？还是一般。我的是南方移动宽带100M。

速度应该不会差与cf worker。具体需要你自己试验。

**Comment by Cptmacmillan2022007** [comment]
创建tunnel提示这个：Error: We cannot process this request as we suspect it was automated. Contact support for more information.怎么破？

**Comment by zizifn** [comment]
> 创建tunnel提示这个：Error: We cannot process this request as we suspect it was automated. Contact support for more information.怎么破？

你绑定信用卡或者PayPal了吗？

**Comment by zhaoguomanong** [comment]
> 创建tunnel提示这个：Error: We cannot process this request as we suspect it was automated. Contact support for more information.怎么破？

绑定完paypal，添加域名路由的时候也提示一样的错误，后来换了个代理ip立马就可以保存了，你可以尝试换个ip操作看看。

**Comment by Cptmacmillan2022007** [comment]
> > 创建tunnel提示这个：Error: We cannot process this request as we suspect it was automated. Contact support for more information.怎么破？
> 
> 你绑定信用卡或者PayPal了吗？

这个我没有绑定啊

**Comment by zizifn** [comment]
> > > 创建tunnel提示这个：Error: We cannot process this request as we suspect it was automated. Contact support for more information.怎么破？
> > 
> > 你绑定信用卡或者PayPal了吗？
> 
> 这个我没有绑定啊

请看你上面一个回复。换个代理IP再去试试?

**Comment by zizifn** [comment]
> 专门回来感谢作者，今天测试配置了一下域名转发绕开 CloudFlare Workers 被墙，也成功了。
> 加上测试首页是对的，这样可以很简单的检测heroku是否正常工作，比以前方便太多。

谢谢。很高兴能帮助到你。

**Comment by DifferentSparkler** [comment]
感觉这个/ ws路径有点危险  要不改成appname这个变量试一试会不会好一些

**Comment by zizifn** [comment]
> 感觉这个/ ws路径有点危险 要不改成appname这个变量试一试会不会好一些

我似乎想到不用path和主页面共存的方式。有时间我试一下。

**Comment by Destroy-God** [comment]
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://): 522 Origin Connection Time-out > websocket: bad handshake] > common/retry: all retry attempts failed
怎么老弹这个
还有貌似Heroku的二级域名herokuapp.com全线完蛋了，估计废了。

**Comment by zizifn** [comment]
> 感觉这个/ ws路径有点危险 要不改成appname这个变量试一试会不会好一些

已经更新，你拉去最近代码，然后试试，记得看下readme，配置章节。已经和首页共享一个path。。

**Comment by Destroy-God** [comment]
最近Heroku是不是严打啊，创的两个号都被封了

**Comment by zizifn** [comment]
> 最近Heroku是不是严打啊，创的两个号都被封了

的确有人反应封号。我账号经常测试，没有被封。如果可以，能否告知，你的使用情况，用的是哪个版本的code?

**Comment by Destroy-God** [comment]
目前最新版的上一个版本

**Comment by zizifn** [comment]
> 目前最新版的上一个版本

拉取下把最新的代码吧。。最新code

1. 每次部署首页都会变。
2. ws path 和主页一样，也就是没有ws path，docker image size也很小。

如果在被封，我也没有办法了。另外尽量不要使用测速软件。

**Comment by redebugzzh** [comment]
> 

用的上一个小猫首页版本，UUID也是自己生成的，利用域名转发绕开 CloudFlare Workers 被墙，7天左右就被封了，每次用完都用stop停掉的，依然不行，还是被封号了，用最新版本部署了一次，看看这次能用多久。

**Comment by ericosmic** [comment]
今天刚试着在github上部署项目，但是一直部署不成功，是因为这种方式被官方封了吗
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/35327931/173276559-54fc77db-5a59-4fa9-8058-5c75552d26ab.png">

**Comment by zizifn** [comment]
> 今天刚试着在github上部署项目，但是一直部署不成功，是因为这种方式被官方封了吗 <img alt="image" width="1311" src="https://user-images.githubusercontent.com/35327931/173276559-54fc77db-5a59-4fa9-8058-5c75552d26ab.png"> <img alt="image" width="1453" src="https://user-images.githubusercontent.com/35327931/173276705-d3bf468a-ca98-4285-a3ff-0fd4119f25fb.png">

你的app name 不符合heroku的规则。错误信息在log中有说明。

**Comment by zizifn** [comment]
heroku 已经不免费的。已经找到新的免费的，感觉不错。请查看，最新code.. 关闭这个issue啦。
