### ISSUE TITLE
脚本支持UDP加速吗？

### ISSUE THREAD

**Issue by Java2Boy** [zizifn/edgetunnel#182]
1：是否支持UDP代理？
2：是否能与UDP2Raw,UDPspeeder搭配加速主机游戏?

参考资料：https://github.com/wangyu-/UDPspeeder/

**Comment by zizifn** [comment]
cloudflare worker 目前不支持 udp。

**Comment by Java2Boy** [comment]
感谢回复

**Comment by CXwudi** [comment]
udp是否可以通过二级代理做到，比如说外面用这个，里面套支持udp的ss

仅仅只是提供个思路，不保证make sense
