### ISSUE TITLE
vless+ws Git Clone 报错

### ISSUE THREAD

**Issue by hululu1068** [zizifn/edgetunnel#201]
GitHub网页能访问，只不过`clone`就报错

```
error: RPC 失败。curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
error: 预期仍然需要 6457 个字节的正文
fetch-pack: unexpected disconnect while reading sideband packet
fatal: 过早的文件结束符（EOF）
fatal: fetch-pack：无效的 index-pack 输出
```
```
error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 预期仍然需要 4707 个字节的正文
fetch-pack: unexpected disconnect while reading sideband packet
fatal: 过早的文件结束符（EOF）
fatal: fetch-pack：无效的 index-pack 输出
```

**Comment by X-MMXXIII** [comment]
我大概找到原因了。。。
```
TCP sockets
The Workers runtime provides the connect() API for creating outbound [TCP connections](https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/) from Workers.

Many application-layer protocols are built on top of the Transmission Control Protocol (TCP). These application-layer protocols, including SSH, MQTT, SMTP, FTP, IRC, and most database wire protocols including MySQL, PostgreSQL, MongoDB, require an underlying TCP socket API in order to work.
```

**Comment by ishell** [comment]
不知道lz解决了没有？我是Clone体积比较大的仓库比如https://github.com/forem/forem 或者https://github.com/gitlabhq/gitlabhq会出现如下这样的错误。体积比较小的仓库没有出现过。
```
正克隆到 'forem'...
remote: Enumerating objects: 155414, done.
remote: Counting objects: 100% (820/820), done.
remote: Compressing objects: 100% (512/512), done.
error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 预期仍然需要 984 个字节的正文
fetch-pack: unexpected disconnect while reading sideband packet
fatal: 过早的文件结束符（EOF）
fatal: fetch-pack：无效的 index-pack 输出
```

```
正克隆到 'gitlabhq'...
remote: Enumerating objects: 2520513, done.
remote: Counting objects: 100% (26309/26309), done.
remote: Compressing objects: 100% (5124/5124), done.
error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 预期仍然需要 5992 个字节的正文
fetch-pack: unexpected disconnect while reading sideband packet
fatal: 过早的文件结束符（EOF）
fatal: fetch-pack：无效的 index-pack 输出
```

**Comment by hululu1068** [comment]
> 不知道lz解决了没有？我是Clone体积比较大的仓库比如https://github.com/forem/forem 或者https://github.com/gitlabhq/gitlabhq 会出现如下这样的错误。体积比较小的仓库没有出现过。
> 
> ```
> 正克隆到 'forem'...
> remote: Enumerating objects: 155414, done.
> remote: Counting objects: 100% (820/820), done.
> remote: Compressing objects: 100% (512/512), done.
> error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
> error: 预期仍然需要 984 个字节的正文
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: 过早的文件结束符（EOF）
> fatal: fetch-pack：无效的 index-pack 输出
> ```
> 
> ```
> 正克隆到 'gitlabhq'...
> remote: Enumerating objects: 2520513, done.
> remote: Counting objects: 100% (26309/26309), done.
> remote: Compressing objects: 100% (5124/5124), done.
> error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
> error: 预期仍然需要 5992 个字节的正文
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: 过早的文件结束符（EOF）
> fatal: fetch-pack：无效的 index-pack 输出
> ```

绕道吧。。。CF有150M的窗口限制

**Comment by ishell** [comment]
> > 不知道lz解决了没有？我是Clone体积比较大的仓库比如https://github.com/forem/forem 或者https://github.com/gitlabhq/gitlabhq 会出现如下这样的错误。体积比较小的仓库没有出现过。
> > ```
> > 正克隆到 'forem'...
> > remote: Enumerating objects: 155414, done.
> > remote: Counting objects: 100% (820/820), done.
> > remote: Compressing objects: 100% (512/512), done.
> > error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
> > error: 预期仍然需要 984 个字节的正文
> > fetch-pack: unexpected disconnect while reading sideband packet
> > fatal: 过早的文件结束符（EOF）
> > fatal: fetch-pack：无效的 index-pack 输出
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 正克隆到 'gitlabhq'...
> > remote: Enumerating objects: 2520513, done.
> > remote: Counting objects: 100% (26309/26309), done.
> > remote: Compressing objects: 100% (5124/5124), done.
> > error: RPC 失败。curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
> > error: 预期仍然需要 5992 个字节的正文
> > fetch-pack: unexpected disconnect while reading sideband packet
> > fatal: 过早的文件结束符（EOF）
> > fatal: fetch-pack：无效的 index-pack 输出
> > ```
> 
> 绕道吧。。。CF有150M的窗口限制

谢谢告知

**Comment by yflwz** [comment]
晕，那是不是说只要是CF的节点就都不能git大的项目
