### ISSUE TITLE
部署后cf worker执行错误率约占70%-80%

### ISSUE THREAD

**Issue by bbbhere** [zizifn/edgetunnel#241]
部署后可以正常使用，但仅仅一天就收到邮件报超过免费10万次请求限制，感觉自己几乎没怎么用不太可能有那么多请求，然后进入CF发现执行请求的成功率只有20%左右，可参考截图提示。
![error-sh2](https://github.com/zizifn/edgetunnel/assets/39181783/31f7bfe4-437f-426f-974a-f3e99747fd8f)
![error-sh3](https://github.com/zizifn/edgetunnel/assets/39181783/0d44987d-5cf1-486d-a160-9e69d6e53903)

**Comment by donkeykangwang10** [comment]
我遇到同样的问题，求解

**Comment by bbbhere** [comment]
这几天观察下来情况有了改善，成功率从20%上升到了80%，所以感觉应该是CF的问题，从源码这边估计无法确定问题，所以我先自己把这个问题关了吧。
