### ISSUE TITLE
iOS 小火箭无法访问？

### ISSUE THREAD

**Issue by 0x000111** [zizifn/edgetunnel#247]
worker搭建的，自定义域名可以访问而且在后面输入uuid也可以得到配置信息，但是导入到小火箭没办法连接。

日志里看到：

proxy stream disconnect reason www.google.com:443 => attempt to connect to host timed out.

有人知道这是什么原因吗？

**Comment by 0x000111** [comment]
close

**Comment by loveholly** [comment]
所以，老哥你最后怎么解决的，我也遇到同样的问题 @0x000111
