### ISSUE TITLE
访问出现您的连接不是私密连接问题

### ISSUE THREAD

**Issue by samon1688** [zizifn/edgetunnel#252]

**Comment by CNKCQ** [comment]
大佬如何解决的？

**Comment by NEPDream** [comment]
请问是如何解决的呀

**Comment by samon1688** [comment]
> 请问是如何解决的呀



> 大佬如何解决的？

我可不是什么大佬，虽然解决了，但并不是从技术层面搞的，说穿了就是换了服务地址，我的经验是有些服务地址会出现私密连接的问题，有些不会，不会出现问题的地址，用一段时间也可能会出现问题，遇到了就换其他的地址，有可能要换很多才能找到一个不出问题的，就是这样，希望有大佬从能找到真正的原因吧。
