### ISSUE TITLE
chatgpt安卓报错disallowed ISP/There is a problem with your reques

### ISSUE THREAD

**Issue by liew9500** [zizifn/edgetunnel#263]
换了CF中转IP，网页端chatgpt正常访问，但是安卓端仍然被锁，我也在网上搜了解决方案，有说套wrap解决的，但是好像没有看到针对v2ray的解决方案，有大神分享下解决方案么

**Comment by ParhamzXc** [comment]
your solution is replacing v2ray/xray core or any client which using xray or v2fly core with Sing-Box
NekoBox is an easy singbox client w/ ui + tons of routing and privacy options. @liew9500

**Comment by liew9500** [comment]
> your solution is replacing v2ray/xray core or any client which using xray or v2fly core with Sing-Box NekoBox is an easy singbox client w/ ui + tons of routing and privacy options. @liew9500
Thx, I'll try it
