### ISSUE TITLE
用自己的VPS配置proxyIP

### ISSUE THREAD

**Issue by vecHao** [zizifn/edgetunnel#269]
步骤如下：
1.准备好一个域名，在VPS上搭建任意网站+配置有效证书，CF上托管域名，并且解析到VPS上，特别注意勾上**穿云箭**，SSL/TLS设置为**完全**。
2.VPS上搭建支持Reality协议的服务端（xray、singbox皆可），配置serverName为自己的域名。
3.proxyIP填VPS的IP，至此所有配置完成。

存在的问题：
1.worker侧应该搞个简单的鉴权，毕竟大家都不希望被别人扫。
2.js中retry实现有点拉跨，访问cdn加速的网站总是慢半拍，这里面包含了等待无响应的时间。

应该有更好的实现方法，我这种只是偷懒用了Reality的副作用，不怎么优雅。

这个方法大家可以试试，用别人IP不如自己的稳定，示例ip数组也总是错误获取到别人的证书。

**Comment by zizifn** [comment]
这种为什么好用啊，用了什么 reality 的副作用

**Comment by zizifn** [comment]
后续会加入 vless 出口，先用着。

**Comment by vecHao** [comment]
> 谢谢，不过这种为什么好用啊，用了什么 reality 的副作用?

相当于设置vps成为cf的一个edge，这并不是reality设计的本意，我觉得算是副作用，效果和无条件转发那些cdn类似，当然别人也可以扫描ip来蹭你的vps来访问cf 代理的网站。

**Comment by 1756171451** [comment]
配置serverName为自己的域名。这一步在哪里阿

**Comment by normanify** [comment]
按此方法可以正常代理，但是部分网站还是会出现SSL错误而无法打开。
