### ISSUE TITLE
能支持自定义dns吗

### ISSUE THREAD

**Issue by xzlosats111** [zizifn/edgetunnel#273]
访问一个网站 5movie.shop ，极其诡异的是cf和谷歌的dns都无法正常解析，国内的腾讯114等反倒可以解析，但是大佬这个脚本生成的节点似乎在v2rayN里设置dns没有效果，不论怎么设置都是去cf的dns

**Comment by Arxhexa** [comment]
https://github.com/zizifn/edgetunnel/blob/74b5b15c77494a81ba29c18a6a7a6580ad63a6fe/src/worker-vless.js#L557

不过更简单的方法应该是添加本地hosts吧，workers我也不太清楚能不能访问国内doh的dns

**Comment by xzlosats111** [comment]
之前就试过了，只修改这一句代码并没有用，ipleak测试出来还是cf的dns，也不知道要改什么，搜索了一下整段代码和dns地址有关的好像也只有这一句了，其他的看不懂
