### ISSUE TITLE
Error 1101 Worker threw exception

### ISSUE THREAD

**Issue by wrackful** [zizifn/edgetunnel#283]
From today, the new worker created with this code will be suspended by cloudflare, I think, and it gives the following error: 
Error 1101 Worker threw exception

What is the solution?

**Comment by marco9989** [comment]
same Error,this afternoon

**Comment by wrackful** [comment]
> 1101 too, have you found any solution?

No, currently no solution has been found and no one is responding anywhere, I am investigating

**Comment by zizifn** [comment]
solved, please check https://github.com/zizifn/edgetunnel/blob/main/src/worker-vless.js

**Comment by zizifn** [comment]
solved, please check https://github.com/zizifn/edgetunnel/blob/main/src/worker-vless.js

**Comment by wrackful** [comment]
> solved, please check https://github.com/zizifn/edgetunnel/blob/main/src/worker-vless.js

Thanks for the reply, but no, the problem has not been solved , please create a new worker and test

**Comment by wrackful** [comment]
I think the problem can be for these 3 functions
stringify
unsafeStringify
isValidUUID

**Comment by wrackful** [comment]
when change return to true is problem solved ,But this is not a principled solution , I am still working on the method
function isValidUUID(uuid) {
	const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
	return true
}

**Comment by zizifn** [comment]
> > solved, please check https://github.com/zizifn/edgetunnel/blob/main/src/worker-vless.js
> 
> Thanks for the reply, but no, the problem has not been solved , please create a new worker and test

from my testing  New script on new worker is working fine. could you test it in new worker?

**Comment by wrackful** [comment]
i tested on new worker , I found the problem, I am searching for the solution, the problem is this code at the beginning of the codes :
`      if (!isValidUUID(userID)) {
        throw new Error('uuid is not valid');
      }  `

**Comment by farahmahmoudm** [comment]
is there any solution for this problem?

**Comment by zizifn** [comment]
> is there any solution for this problem?

https://github.com/zizifn/edgetunnel/issues/283#issuecomment-2088814329

please create new worker and try it with updated code

**Comment by ECS-tasy** [comment]
我去年用的老的代码，开了两个workers，绑的不同的proxyIP。其中一个proxyIP失效了，我没改，用了一段时间，突然有天翻不了了，我就一直用另一个。今天发现那个翻不了的原来error 1101了。
如果说是识别代码把我ban掉的话，另一个worker好好的，难道是因为长期没走proxyIP被识别出来异常使用？

**Comment by Tmalll** [comment]
> isValidUUID

大佬, 使用socks5那个脚本有这个问题
workers测试的时候正常
![image](https://github.com/user-attachments/assets/678ddd5a-d930-4f4e-a048-4c1ef454ef73)

浏览器访问就1101
![image](https://github.com/user-attachments/assets/5ab6317c-50bd-42a3-9f96-1c9b252dae04)

然后同样的配置用不带socks5那个脚本就一切正常

**Comment by zizifn** [comment]
最新 code 吗？

**Comment by zizifn** [comment]
socket5 我没更新，我今晚更新下吧

**Comment by zizifn** [comment]
> > isValidUUID
> 
> 大佬, 使用socks5那个脚本有这个问题
> workers测试的时候正常
> ![image](https://github.com/user-attachments/assets/678ddd5a-d930-4f4e-a048-4c1ef454ef73)
> 
> 浏览器访问就1101
> ![image](https://github.com/user-attachments/assets/5ab6317c-50bd-42a3-9f96-1c9b252dae04)
> 
> 然后同样的配置用不带socks5那个脚本就一切正常
> 

应该可以了，你试试

**Comment by Tmalll** [comment]
> > > isValidUUID
> > 
> > 
> > 大佬, 使用socks5那个脚本有这个问题
> > workers测试的时候正常
> > ![image](https://private-user-images.githubusercontent.com/40192806/375353212-678ddd5a-d930-4f4e-a048-4c1ef454ef73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzIwNzQsIm5iZiI6MTcyODYzMTc3NCwicGF0aCI6Ii80MDE5MjgwNi8zNzUzNTMyMTItNjc4ZGRkNWEtZDkzMC00ZjRlLWEwNDgtNGMxZWY0NTRlZjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmFhMjlmOTJiNGIwODI2ZTAwZjdkNmI5M2Q0Y2U1YTkzZmExNmZjNzVkN2Q1NTY0MWQ5Y2U1Y2QyNjQyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ejdWgeUGUTROYzvU818avEN3QP2xHxDwQ5gN0a5L_sQ)
> > 浏览器访问就1101
> > ![image](https://private-user-images.githubusercontent.com/40192806/375353354-5ab6317c-50bd-42a3-9f96-1c9b252dae04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzIwNzQsIm5iZiI6MTcyODYzMTc3NCwicGF0aCI6Ii80MDE5MjgwNi8zNzUzNTMzNTQtNWFiNjMxN2MtNTBiZC00MmEzLTlmOTYtMWM5YjI1MmRhZTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNWY2NjJhMWZkMDcyZWM2ODdjZGZjNTk5NDIyZDY5MmNiNmNlNGQ2NWRkMWM1ZmE5OGUzNThjYjI2NDQxZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2ITfVbesA_tyw5sIVLtaVzLqkV5XofmLQyims_RpfC0)
> > 然后同样的配置用不带socks5那个脚本就一切正常
> 
> 应该可以了，你试试

ok, 好了!能用了!

**Comment by kyawswarthwin** [comment]
11/24/2024 Just today, the same Error 1101 is coming up again.

**Comment by wrackful** [comment]
I encountered this problem again, can it be fixed?
