### ISSUE TITLE
【功能建议】增加一个域名列表强制走代理IP

### ISSUE THREAD

**Issue by pan8664716** [zizifn/edgetunnel#289]
因为cf worker的特性，ip会来回跳，所以导致一些应用我们无法使用。比如gemini，twitter（虽然可以使用，但是IP总在改变有风险）！希望增加一个白名单列表，可以强制走代理IP！

但是我研究了一下代码，通过添加一些日志并没有找到网址的IP，期间打印了request.header 以及 addressremote 等变量！作者可以给一些思路吗？

**Comment by zizifn** [comment]
代理 ip 只能代理 cloudfalre 网站，你这种需求需要看另一个文件
https://github.com/zizifn/edgetunnel/blob/main/src/worker-with-socks5-experimental.js
