### ISSUE TITLE
100M自动断

### ISSUE THREAD

**Issue by wx69wx** [zizifn/edgetunnel#296]
使用它进行scp拷贝大文件时，总是在100M左右失去连接。。。
反复测试确定只在使用这种节点出现，是有什么设置吗？望大佬指点迷津，谢谢！

**Comment by zizifn** [comment]
没有办法。大文件因为 websocket 没有支持 stream，会造成 cpu 超时。

**Comment by linhua55** [comment]
在cpu超时之前或之后，创建新的websocket connection，使用新的connection继续传输是否可行
