### ISSUE TITLE
~Cloudflare优选IP分享~

### ISSUE THREAD

**Issue by momo54181** [zizifn/edgetunnel#302]
Cloudflare优选IP分享
目前IP已经整合到一个域名：******.******.***
测试地点：**
博客文章：*************************

**Comment by momo54181** [comment]
哪位老哥偷偷摸摸的
![image](https://github.com/user-attachments/assets/47b7dfd7-1353-4b24-89e2-e36b1645cdd8)

**Comment by momo54181** [comment]
![image](https://github.com/user-attachments/assets/a068a348-fa56-4f7c-ac4a-d76209a346d2)
你以为的隐藏，实际上是会传输你的真实IP

**Comment by cyclestudy** [comment]
> Cloudflare优选IP分享 目前IP已经整合到一个域名：**.**.*** 测试地点：** 博客文章：*************************

怎么隐藏看不到了
