### ISSUE TITLE
有概率出现错误页面

### ISSUE THREAD

**Issue by xzlosats111** [zizifn/edgetunnel#305]
使用此项目搭建的节点访问cf的网站甚至不是cf网站只是用了cf盾，有概率出现如下画面
![2024-07-06_233616](https://github.com/zizifn/edgetunnel/assets/126597684/f2c24b72-097b-4d7c-9c7c-1cb3f6df5063)
虽然重启浏览器，重连节点即可解决
但似乎cf cdn内部错误，毕竟证书都是没问题的，可大可小的问题，好奇问一问

**Comment by zizifn** [comment]
大概是 proxyIP 问题，cf 盾也是需要访问 cf ip 的

**Comment by xzlosats111** [comment]
是的，就是，我用的优选域名，重连就是为了重新随机一个能用的ip出来，只是好奇为什么有时证书报错，有时不报错，这要上纲上线的话算是挺严重的错误了把，觉得挺有意思，本身很好解决

**Comment by zizifn** [comment]
> 是的，就是，我用的优选域名，重连就是为了重新随机一个能用的ip出来，只是好奇为什么有时证书报错，有时不报错，这要上纲上线的话算是挺严重的错误了把，觉得挺有意思，本身很好解决

proxy ip 不是一个可信的 ip 中转，有人是可以在上面做中间人攻击的。但是正规浏览器会保护你，如果出现证书错误不要强行忽略。
