### ISSUE TITLE
const earlyDataHeader = request.headers.get('sec-websocket-protocol') || '';  is always empty

### ISSUE THREAD

**Issue by mojocn** [zizifn/edgetunnel#324]
const earlyDataHeader = request.headers.get('sec-websocket-protocol') || '';  is always empty

earlyDataHeader  is reduntant.

**Comment by zizifn** [comment]
this is support  ws 0-RTT. 

https://xtls.github.io/en/config/transports/websocket.html#websocketobject

> If path contains the ed query parameter, early data will be activated for latency reduction, and its value will be the length threshold of the first packet. If the length of the first packet exceeds this value, early data won't be activated. The recommended value is 2560, with a maximum of 8192. Compatibility problems can occur when the value is set too high. Try lowering the threshold when encountering such problems.
