### ISSUE TITLE
Error 1101

### ISSUE THREAD

**Issue by kyawswarthwin** [zizifn/edgetunnel#331]
11/24/2024: Encountering Error 1101 again today.

**Comment by cnszlijz** [comment]
I also encountered this situation. The project cmliu/edgetunnel deployed obfuscation yesterday and now it can work properly. It seems cloudflare is blocking this script.

**Comment by TodDod** [comment]
最近yonggekkk也是这个错误，看样子不是个例

**Comment by claudehotline** [comment]
11/26 新部署的报Error 1101 以前部署的可以用

**Comment by zizifn** [comment]
should be working fine now. please try.

**Comment by showgood163** [comment]
Tried the latest js commit b87ac3b, reported error 1101

**Comment by zizifn** [comment]
> Tried the latest js commit [b87ac3b](https://github.com/zizifn/edgetunnel/commit/b87ac3b16381889340cf6ace191dc97e188fcff7), reported error 1101

From my testing, current main branch code working fine. Could you delete worker and create new one?

**Comment by showgood163** [comment]
> > Tried the latest js commit [b87ac3b](https://github.com/zizifn/edgetunnel/commit/b87ac3b16381889340cf6ace191dc97e188fcff7), reported error 1101
> 
> From my testing, current main branch code working fine. Could you delete worker and create new one?

Did you obfuscate the js or not?

**Comment by zizifn** [comment]
> > > Tried the latest js commit [b87ac3b](https://github.com/zizifn/edgetunnel/commit/b87ac3b16381889340cf6ace191dc97e188fcff7), reported error 1101
> > 
> > 
> > From my testing, current main branch code working fine. Could you delete worker and create new one?
> 
> Did you obfuscate the js or not?

No, I'm not like obfuscate source code.

**Comment by showgood163** [comment]
> > > > Tried the latest js commit [b87ac3b](https://github.com/zizifn/edgetunnel/commit/b87ac3b16381889340cf6ace191dc97e188fcff7), reported error 1101
> > > 
> > > 
> > > From my testing, current main branch code working fine. Could you delete worker and create new one?
> > 
> > 
> > Did you obfuscate the js or not?
> 
> No, I'm not like obfuscate source code.

Very strange. Yesterday I copied the js into a repo, deployed the pages and it reported 1101.
Now I manually copy the js and deploy a worker and it works.

**Comment by HenTele** [comment]
It happened again just half an hour ago.

**Comment by HenTele** [comment]
```txt
inbound/mixed[1]: process connection from 10.1.1.197:49503: unexpected HTTP response status: 522
```

**Comment by showgood163** [comment]
My worker also stops working.

**Comment by wrackful** [comment]
I have this problem and I get error 1101.
