### ISSUE TITLE
关于封号的事

### ISSUE THREAD

**Issue by 362227** [zizifn/edgetunnel#43]
就是走大流量的被封了，我很多项目都被封了，只要涉及下载、上传，而且自heroku出事后这个限制很严格，好像长时间（几分钟都算）跑1-2M/S以上都会被封。除非你就浏览网页，不看高清视频

**Comment by zizifn** [comment]
heroku是我备用，等我试一把。。

**Comment by wayne0926** [comment]
切忌跑大流量！！！！！！！！！！！！！！！！
我还发个邮件去问，结果被反问，尴尬死我😅

**Comment by redebugzzh** [comment]
> 
回复怎么说的？

**Comment by redebugzzh** [comment]
> 切忌跑大流量！！！！！！！！！！！！！！！！ 我还发个邮件去问，结果被反问，尴尬死我😅


回复怎么说的？

**Comment by idolyuri** [comment]
一样被封

**Comment by jiange1236** [comment]
被封+1

**Comment by performcanhe** [comment]
> 切忌跑大流量！！！！！！！！！！！！！！！！ 我还发个邮件去问，结果被反问，尴尬死我sweat_smile

把反问贴出来看看呗

我反正没好意思发邮件去问

**Comment by wayne0926** [comment]
> > 切忌跑大流量！！！！！！！！！！！！！！！！ 我还发个邮件去问，结果被反问，尴尬死我sweat_smile
> 
> 把反问贴出来看看呗
> 
> 我反正没好意思发邮件去问

![image](https://user-images.githubusercontent.com/63389859/173867178-2c5784a6-9db4-4c9d-9c4e-f1c1e89567cf.png)

我之前也不知道它是奔着封号去的啊，我没关注这个问题，主要是之前用了很久都没有任何问题，以为可能是什么技术故障……

**Comment by wayne0926** [comment]
话说我新创了一个账号，然后没跑大流量（全部控制在1m/s一下），我用完之后stop了，再打开就已经封号了……
没法了

**Comment by performcanhe** [comment]
我有个账号也突然被封了。也不清楚封锁的规律。
看这个回复确实有点尴尬。

**Comment by williamzjr** [comment]
> > 我用不同的帐号部署，最早部署的一直在用，后面用其他账号部署，最长不过一周，不管是不是大流量都被封杀。 邮件反馈过多次没用，看来以后只能付费了。
> > >
> 
> 我试了几十个账号，没有违规的app，跑大流量会被封。违规的app（比如qbtorrent、aria、ssr、v2ray），稍微用一下就会被封。看你们的回复，v2ray应该属于违规的app。 然后付费和免费一样的待遇，一样会被封，我测试过

目前有个一帐号也是跑v2ray，相同的代码，一直用到现在没事，其他的不行，所以真的找不出规律，我的手机号都已经很难再去注册新的gmail帐号了

**Comment by redebugzzh** [comment]
注册了个新账号，部署到现在10多天了，一直没敢上油管看视频，到今天为止还健在。

感觉可能真的是流量的问题。

**Comment by zizifn** [comment]
> > heroku是我备用，等我试一把。。
> 
> 请问除了Heroku, 还有哪些平台提供免费服务可以用来部署的？heroku封号有点狠

Okteto Cloud？

**Comment by zizifn** [comment]
真让我开新坑？我个人看youtube是没有封号的。。

**Comment by performcanhe** [comment]
我新建了一个，一直看youtube也没事。

**Comment by zizifn** [comment]
如果有人有时间，愿意帮忙做测试，我可以为每个免费服务创建一套github action。。

**Comment by 362227** [comment]
> > > 我用不同的帐号部署，最早部署的一直在用，后面用其他账号部署，最长不过一周，不管是不是大流量都被封杀。 邮件反馈过多次没用，看来以后只能付费了。
> > > >
> > 
> > 
> > 我试了几十个账号，没有违规的app，跑大流量会被封。违规的app（比如qbtorrent、aria、ssr、v2ray），稍微用一下就会被封。看你们的回复，v2ray应该属于违规的app。 然后付费和免费一样的待遇，一样会被封，我测试过
> 
> 目前有个一帐号也是跑v2ray，相同的代码，一直用到现在没事，其他的不行，所以真的找不出规律，我的手机号都已经很难再去注册新的gmail帐号了

我也有这种账号，比较早注册的，疯狂跑流量都没事，一个月跑100TB都好像没事，不敢部署新app了，感觉这种账号是宝

**Comment by 362227** [comment]
> 如果有人有时间，愿意帮忙做测试，我可以为每个免费服务创建一套github action。。自动化部署。

感觉没必要折腾了，我测试了很多github项目，还有自己整的，基本上可以断定是走大流量封，而且敏感的项目更容易封号。当然有一些账号是有bug的，不容易被封，但很少很少，看人品

**Comment by zizifn** [comment]
> > 如果有人有时间，愿意帮忙做测试，我可以为每个免费服务创建一套github action。。自动化部署。
> 
> 感觉没必要折腾了，我测试了很多github项目，还有自己整的，基本上可以断定是走大流量封，而且敏感的项目更容易封号。当然有一些账号是有bug的，不容易被封，但很少很少，看人品

我指的是除了heroku其他家的服务。。

**Comment by zhere** [comment]
今早发现被封了 ，钉钉邮箱注册的， 连个 封号邮件都没有 收到；修改密码后 仍然 提示 Couldn't find that user.

**Comment by dfbucy090** [comment]
> 如果有人有时间，愿意帮忙做测试，我可以为每个免费服务创建一套github action。。自动化部署。

再观察一下吧，我几十个账号封了还剩10来个，没有规律可循，我基本都不怎么用，只是定期检查一下，现在又注册了几个，还没有部署，反正也不当主力用，看到底能否封完我剩下的。也可能过一段时间就没啥事了。

**Comment by redebugzzh** [comment]
> 

okteto前面用过，速度卡，而且不稳定，现在还真不知道哪家比heroku强的

**Comment by williamzjr** [comment]
全程部署都是走代理，新部署的两个帐号一天后就挂了，没有任何邮件告知，这次用的是proton的邮箱。
现在就剩一个老帐号独苗，再挂就没得办法翻出来了

**Comment by huLter** [comment]
我已经被封了4个账号了，直接提示 Couldn't find that user. 
我试试在配置文件限一下速行不行

**Comment by lostknife1992** [comment]
封号严重，跑大流量直接BAN，有其他免费平台可以用吗？大佬写一个吧，偶尔看下油管

**Comment by zizifn** [comment]
> 封号严重，跑大流量直接BAN，有其他免费平台可以用吗？大佬写一个吧，偶尔看下油管

ok... fine..我去找一个。。

**Comment by zizifn** [comment]
> > 封号严重，跑大流量直接BAN，有其他免费平台可以用吗？大佬写一个吧，偶尔看下油管
> 
> ok... fine..我去找一个。。

Okteto Cloud 秒封。。ok。。有点难办，对比下来，heroku 还是很良心的。如果这样，还想免费，只能拿信用卡注册几大云厂商的账户，然后用他们的。

**Comment by lostknife1992** [comment]
免费的PaaS    
Koyeb: koyeb.com
Render: render.com
Railway: railway.app
Repl.it: replit.com
都可以免费创建容器
大佬帮忙搞一下吧

**Comment by zizifn** [comment]
> 免费的PaaS    
> Koyeb: koyeb.com
> Render: render.com
> Railway: railway.app
> Repl.it: replit.com
> 都可以免费创建容器
> 大佬帮忙搞一下吧

你喜欢哪一个？

**Comment by Cptmacmillan2022007** [comment]
不要同时使用caddy/nginx反代的同时使用v2/xray

这种被ban掉的几率更高

让v2/xray监听0.0.0.0

**Comment by zizifn** [comment]
> 不要在部署caddy/nginx反代的同时使用v2/xray
> 
> 这种被ban掉的几率更高
> 
> 让v2/xray监听0.0.0.0

LOL....如果你翻看我的issue 记录，直接都是监听，0.0.0.0， 加caddy/nginx 是为了满足自定义首页，也是为了ban。。所以玄学。

**Comment by Cptmacmillan2022007** [comment]
> > 免费的PaaS
> > Koyeb: koyeb.com
> > Render: render.com
> > Railway: railway.app
> > Repl.it: replit.com
> > 都可以免费创建容器
> > 大佬帮忙搞一下吧
> 
> 你喜欢哪一个？

你推荐这几个容器云都支持http2路由
可以考虑下http2的配置

**Comment by zizifn** [comment]
> > > 免费的PaaS
> > > Koyeb: koyeb.com
> > > Render: render.com
> > > Railway: railway.app
> > > Repl.it: replit.com
> > > 都可以免费创建容器
> > > 大佬帮忙搞一下吧
> > 
> > 
> > 你喜欢哪一个？
> 
> 你推荐这几个容器云都支持http2路由 可以考虑下http2的配置 第1和第4个有tls支持 可以好好利用下这个特性

考虑了。现在的repo code 预留了 h2的口子。已经在做了。

**Comment by zizifn** [comment]
> 免费的PaaS Koyeb: koyeb.com Render: render.com Railway: railway.app Repl.it: replit.com 都可以免费创建容器 大佬帮忙搞一下吧

 railway.app-->直接检测code是否含有v2ray
replit.com-->貌似没有办法允许docker
koyeb.com--》账户申请在审核，但是他们TOS，不允许proxy程序，申请后在试试。
render.com -》在尝试怎么允许docker。应该可以。

**Comment by Cptmacmillan2022007** [comment]
> > 免费的PaaS Koyeb: koyeb.com Render: render.com Railway: railway.app Repl.it: replit.com 都可以免费创建容器 大佬帮忙搞一下吧
> 
> railway.app-->直接检测code是否含有v2ray replit.com-->貌似没有办法允许docker koyeb.com--》账户申请在审核，但是他们TOS，不允许proxy程序，申请后在试试。 render.com -》在尝试怎么允许docker。应该可以。

可以试一下render

有heroku迁移指南

不知道是不是可以改改直接就能用。

没有在网站上看到http路由版本

**Comment by zizifn** [comment]
> > > 免费的PaaS Koyeb: koyeb.com Render: render.com Railway: railway.app Repl.it: replit.com 都可以免费创建容器 大佬帮忙搞一下吧
> > 
> > 
> > railway.app-->直接检测code是否含有v2ray replit.com-->貌似没有办法允许docker koyeb.com--》账户申请在审核，但是他们TOS，不允许proxy程序，申请后在试试。 render.com -》在尝试怎么允许docker。应该可以。
> 
> 可以试一下render
> 
> 有heroku迁移指南
> 
> 不知道是不是可以改改直接就能用。
> 
> 没有在网站上看到http路由版本

render 虽然能部署，但是短时间render 账户就被logout，然后再也登录不进去。

**Comment by zizifn** [comment]
> > > 免费的PaaS Koyeb: koyeb.com Render: render.com Railway: railway.app Repl.it: replit.com 都可以免费创建容器 大佬帮忙搞一下吧
> > 
> > 
> > railway.app-->直接检测code是否含有v2ray replit.com-->貌似没有办法允许docker koyeb.com--》账户申请在审核，但是他们TOS，不允许proxy程序，申请后在试试。 render.com -》在尝试怎么允许docker。应该可以。
> 
> 可以试一下render
> 
> 有heroku迁移指南
> 
> 不知道是不是可以改改直接就能用。
> 
> 没有在网站上看到http路由版本

https://github.com/zizifn/v2-deploy 如果你想实验，可以试试，记得在render 环境中加入两个环境变量，
PORT  8888
UUID  你自己生成一个

**Comment by Cptmacmillan2022007** [comment]
> > > > 免费的PaaS Koyeb: koyeb.com Render: render.com Railway: railway.app Repl.it: replit.com 都可以免费创建容器 大佬帮忙搞一下吧
> > > 
> > > 
> > > railway.app-->直接检测code是否含有v2ray replit.com-->貌似没有办法允许docker koyeb.com--》账户申请在审核，但是他们TOS，不允许proxy程序，申请后在试试。 render.com -》在尝试怎么允许docker。应该可以。
> > 
> > 
> > 可以试一下render
> > 有heroku迁移指南
> > 不知道是不是可以改改直接就能用。
> > 没有在网站上看到http路由版本
> 
> https://github.com/zizifn/v2-deploy 如果你想实验，可以试试，记得在render 环境中加入两个环境变量， PORT 8888 UUID 你自己生成一个

ok

**Comment by performcanhe** [comment]
> > > 封号严重，跑大流量直接BAN，有其他免费平台可以用吗？大佬写一个吧，偶尔看下油管
> > 
> > 
> > ok... fine..我去找一个。。
> 
> Okteto Cloud 秒封。。ok。。有点难办，对比下来，heroku 还是很良心的。如果这样，还想免费，只能拿信用卡注册几大云厂商的账户，然后用他们的。

几大云厂商的可以稳定跑不删档吗？一般他们都有免费流量的，不删档的话，也可以用用的。

**Comment by lc09cn** [comment]
刷刷google查询也会被BAN

**Comment by q3128923436** [comment]
> > > 我用不同的帐号部署，最早部署的一直在用，后面用其他账号部署，最长不过一周，不管是不是大流量都被封杀。 邮件反馈过多次没用，看来以后只能付费了。
> > > >
>  
> > 
> > 我试了几十个账号，没有违规的app，跑大流量会被封。违规的app（比如qbtorrent、aria、ssr、v2ray），稍微用一下就会被封。看你们的回复，v2ray应该属于违规的app。 然后付费和免费一样的待遇，一样会被封，我测试过
> 
> 目前有个一帐号也是跑v2ray，相同的代码，一直用到现在没事，其他的不行，所以真的找不出规律，我的手机号都已经很难再去注册新的gmail帐号了

苹果的iCloud+可以无限开隐藏地址，要每月0.99刀至少

**Comment by Cptmacmillan2022007** [comment]
heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
继续使用heroku必须要升级到付费账户。
或出门右转接着白嫖。

**Comment by zizifn** [comment]
> heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> 继续使用heroku必须要升级到付费账户。
> 或出门右转接着寻找下一个可以白嫖的服务。
> 
> 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> 
> 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> 
> ======================以下是heroku发的原始电邮======================
> Dear Customer,
> 
> Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> 
> Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> 
> For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> 
> Thank you,
> 
> The Heroku Team
> 

早上看到了。项目死了。等我有时间，把项目archive吧。

**Comment by Cptmacmillan2022007** [comment]
> > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > 继续使用heroku必须要升级到付费账户。
> > 或出门右转接着寻找下一个可以白嫖的服务。
> > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > ======================以下是heroku发的原始电邮======================
> > Dear Customer,
> > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > Thank you,
> > The Heroku Team
> 
> 早上看到了。项目死了。等我有时间，把项目archive吧。

可以白嫖的还有多少啊？
越来越难找了

**Comment by zizifn** [comment]
> > > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > > 继续使用heroku必须要升级到付费账户。
> > > 或出门右转接着寻找下一个可以白嫖的服务。
> > > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > > ======================以下是heroku发的原始电邮======================
> > > Dear Customer,
> > > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > Thank you,
> > > The Heroku Team
> > 
> > 早上看到了。项目死了。等我有时间，把项目archive吧。
> 
> 可以白嫖的还有多少啊？
> 越来越难找了

白嫖太难了。heroku算是最大方的，其他很多都秒封。

**Comment by Cptmacmillan2022007** [comment]
可以试下koyeb

ssl那边得下点功夫

**Comment by Cptmacmillan2022007** [comment]
试下这几个

https://www.cyclic.sh/

https://www.deta.sh/

http://fly.io/

**Comment by dfbucy090** [comment]
> > > > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > > > 继续使用heroku必须要升级到付费账户。
> > > > 或出门右转接着寻找下一个可以白嫖的服务。
> > > > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > > > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > > > ======================以下是heroku发的原始电邮======================
> > > > Dear Customer,
> > > > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > > > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > Thank you,
> > > > The Heroku Team
> > > 
> > > 
> > > 早上看到了。项目死了。等我有时间，把项目archive吧。
> > 
> > 
> > 可以白嫖的还有多少啊？
> > 越来越难找了
> 
> 白嫖太难了。heroku算是最大方的，其他很多都秒封。

大侠还是研究一下Koyeb,他家对老帐户不封号，只是用别人提供的部署最近不行了，请大侠能提供新的方法。

**Comment by Cptmacmillan2022007** [comment]
> > > > > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > > > > 继续使用heroku必须要升级到付费账户。
> > > > > 或出门右转接着寻找下一个可以白嫖的服务。
> > > > > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > > > > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > > > > ======================以下是heroku发的原始电邮======================
> > > > > Dear Customer,
> > > > > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > > > > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > Thank you,
> > > > > The Heroku Team
> > > > 
> > > > 
> > > > 早上看到了。项目死了。等我有时间，把项目archive吧。
> > > 
> > > 
> > > 可以白嫖的还有多少啊？
> > > 越来越难找了
> > 
> > 
> > 白嫖太难了。heroku算是最大方的，其他很多都秒封。
> 
> 大侠还是研究一下Koyeb,他家对老帐户不封号，只是用别人提供的部署最近不行了，请大侠能提供新的方法。

koyeb没有办法配置tls（可能是paid用户独享）

比heroku较好的一点是可以支持http2/grpc但还是会卡在tls问题上

**Comment by dfbucy090** [comment]
好像有tls，我配置是打勾的，是用docker 部署的，源码我看不懂，只是照葫芦画瓢，可以使用cf CDN。

Cptmacmillan2022007 ***@***.***> 于2022年10月18日周二 14:17写道：

**Comment by dfbucy090** [comment]
> > > > > > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > > > > > 继续使用heroku必须要升级到付费账户。
> > > > > > 或出门右转接着寻找下一个可以白嫖的服务。
> > > > > > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > > > > > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > > > > > ======================以下是heroku发的原始电邮======================
> > > > > > Dear Customer,
> > > > > > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > > > > > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > > Thank you,
> > > > > > The Heroku Team
> > > > > 
> > > > > 
> > > > > 早上看到了。项目死了。等我有时间，把项目archive吧。
> > > > 
> > > > 
> > > > 可以白嫖的还有多少啊？
> > > > 越来越难找了
> > > 
> > > 
> > > 白嫖太难了。heroku算是最大方的，其他很多都秒封。
> > 
> > 
> > 大侠还是研究一下Koyeb,他家对老帐户不封号，只是用别人提供的部署最近不行了，请大侠能提供新的方法。
> 
> koyeb没有办法配置tls（可能是paid用户独享）
> 
> 比heroku较好的一点是可以支持http2/grpc但还是会卡在证书问题上
> 
> 不能手动配置证书的容器不是好容器！

好像有tls，我配置是打勾的，是用docker 部署的，源码我看不懂，只是照葫芦画瓢，可以使用cf CDN。
![捕获](https://user-images.githubusercontent.com/70613514/196562844-c2c080fd-71c4-4c74-bec5-e9d67f20edb8.JPG)

**Comment by Cptmacmillan2022007** [comment]
> > > > > > > heroku从2022/11/28之后不再提供免费dyno，已有项目会停止运行。
> > > > > > > 继续使用heroku必须要升级到付费账户。
> > > > > > > 或出门右转接着寻找下一个可以白嫖的服务。
> > > > > > > 从 2022 年 11 月 28 日开始，免费 Heroku Dynos、免费 Heroku Postgres 和免费 Heroku Data for Redis® 将不再可用。 您可以在 Heroku 博客上从我们的总经理 Bob Wise 那里了解更多关于这些和其他重要变化的信息。
> > > > > > > 现有的免费 dynos 和 Heroku 数据插件将受到影响，因此需要您采取行动。 为防止使用免费计划对您的应用程序或数据造成任何干扰，您需要在 2022 年 11 月 28 日之前从免费计划升级到付费计划。
> > > > > > > ======================以下是heroku发的原始电邮======================
> > > > > > > Dear Customer,
> > > > > > > Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available. You can learn more about these and other important changes from our GM, Bob Wise, on the [Heroku blog](https://hello.heroku.com/e/36622/next-chapter/m49jcf/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > > > Existing free dynos and Heroku data add-ons will be impacted, so action by you is required. To prevent any disruption to your apps or data using free plans, you will need to upgrade from a free plan to a paid plan before November 28, 2022.
> > > > > > > For instructions on how to upgrade and for other questions, please [visit our FAQ](https://hello.heroku.com/e/36622/-heroku-free-product-plans-faq/m49jcj/1136326260?h=zGiJLUky8eAM9wvZKA_o6w-INVdo-nuUjWtEGqF_oXk).
> > > > > > > Thank you,
> > > > > > > The Heroku Team
> > > > > > 
> > > > > > 
> > > > > > 早上看到了。项目死了。等我有时间，把项目archive吧。
> > > > > 
> > > > > 
> > > > > 可以白嫖的还有多少啊？
> > > > > 越来越难找了
> > > > 
> > > > 
> > > > 白嫖太难了。heroku算是最大方的，其他很多都秒封。
> > > 
> > > 
> > > 大侠还是研究一下Koyeb,他家对老帐户不封号，只是用别人提供的部署最近不行了，请大侠能提供新的方法。
> > 
> > 
> > koyeb没有办法配置tls（可能是paid用户独享）
> > 比heroku较好的一点是可以支持http2/grpc但还是会卡在证书问题上
> > 不能手动配置证书的容器不是好容器！
> 
> 好像有tls，我配置是打勾的，是用docker 部署的，源码我看不懂，只是照葫芦画瓢，可以使用cf CDN。 ![捕获](https://user-images.githubusercontent.com/70613514/196562844-c2c080fd-71c4-4c74-bec5-e9d67f20edb8.JPG)

你这是客户端，服务端你能手动配置tls security并载入证书

不会出现client send an http request to https server的提示吗

还有容器runtime log出现tls handshake error的提升吗

只有服务端和客户端都开了tls才是真的tls

不然服务端早晚会被某fw给探测出来的

**Comment by Cptmacmillan2022007** [comment]
> 试下这几个
> 
> 注意下他们的Team of services还有http version和ssl
> 
> https://www.cyclic.sh/
> 
> https://www.deta.sh/
> 
> ~~http://fly.io/~~官方警告搭建代理是收费服务不要继续了

**Comment by Cptmacmillan2022007** [comment]
> 试下这几个
> 
> 注意下他们的Team of services还有http version和ssl
> 
> https://www.cyclic.sh/
> 
> https://www.deta.sh/
> 
> <del>http://fly.io/</del>官方警告搭建代理应用是收费服务，大家再找找别的免费的容器吧

**Comment by Cptmacmillan2022007** [comment]
<del>replit.com</del>禁止创建代理类服务应用

**Comment by zizifn** [comment]
我上周末试验了，使用nodejs 来作为代理。本地和我自己的server实现成功。
但是部署到vercel这种serveless的平台上，怎么都成功不了。

可能是代码写的有问题。也可能是vercel不知道streaming http request body。。
我在研究下，如果成功，那么白嫖党就可以在续命很久，因为免费提供serverless function的厂商有不少家。

**Comment by zizifn** [comment]
已经找到新的免费的，感觉不错。请查看，最新code..

**Comment by DFP86** [comment]
There was a problem with your login.

↑我估计也是被封了，但一直都是这个提示
我反正用不了但我登不上去。。。还不断给我发邮件说我只有一个二步验证看上去不太够，不断发不断发，我邮箱都几百封了
