### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by metaschoolboy01** [zizifn/edgetunnel#48]
Heroku says We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by zizifn** [comment]
你是怎么部署的，请不要在我的仓库下点部署。
1. fork项目，改个名字
2. 如果不可以，请参考文档使用action 部署。

**Comment by zizifn** [comment]
hheroku 已经不免费了。已经找到新的免费的，感觉不错。请查看，最新code..
