### ISSUE TITLE
用tunnel美服的失败欧服的没问题

### ISSUE THREAD

**Issue by 1779587460** [zizifn/edgetunnel#49]
照着设置来了，访问tunnel的域名显示There's nothing here, yet.，欧服的是伪装网页，在v2ray上也是美服的有问题

**Comment by 1779587460** [comment]
把heroku的项目名改下解决了，能访问伪装网页和加速，但过不久访问变成Application error，内容是An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
加速也无法使用了
部署时是直接fork的，除了要添加的那几项其他都没动过

**Comment by zizifn** [comment]
先别tunnel。。试试看。

**Comment by 1779587460** [comment]
emm不用tunnel的话还是那个报错用不了，可能是伪装网页出错了，导致整个程序用不了？

**Comment by zizifn** [comment]
> emm不用tunnel的话还是那个报错用不了，可能是伪装网页出错了，导致整个程序用不了？

我的意思，不加tunnel开关。然后试试看。

**Comment by zizifn** [comment]
heroku 已经不免费了，找到了一个新的免费方案，如果有需要，请查看最新code...
