### ISSUE TITLE
https://mogenius.com/home 这个现在不需要验证手机了

### ISSUE THREAD

**Issue by 8ty** [zizifn/edgetunnel#51]
大佬打算试试吗? @zizifn

**Comment by Jianyuann** [comment]
部署了一个，能用，只有5G流量。

https://github.com/Jianyuann/docker-xray

![image](https://user-images.githubusercontent.com/9197609/191013015-81bb577d-dfb9-4d90-8525-50d9466793e5.png)

**Comment by srsdkfsa** [comment]
> 部署了一个，能用，只有5G流量。
> 
> https://github.com/Jianyuann/docker-xray
> 
> ![image](https://user-images.githubusercontent.com/9197609/191013015-81bb577d-dfb9-4d90-8525-50d9466793e5.png)

麻烦出下具体教程？

**Comment by 8ty** [comment]
> 部署了一个，能用，只有5G流量。
> 
> https://github.com/Jianyuann/docker-xray
> 
> ![image](https://user-images.githubusercontent.com/9197609/191013015-81bb577d-dfb9-4d90-8525-50d9466793e5.png)


为什么我部署了总是会偶尔就stop？

**Comment by 8ty** [comment]
> 部署了一个，能用，只有5G流量。
> 
> https://github.com/Jianyuann/docker-xray
> 
> ![image](https://user-images.githubusercontent.com/9197609/191013015-81bb577d-dfb9-4d90-8525-50d9466793e5.png)

不知道为什么刚刚用了一会可以，后面就不行了，网页是能正常打开Bad Request，但是客户端io: read/write on closed pipe

可能是需要矫正时间？

**Comment by zizifn** [comment]
> > 部署了一个，能用，只有5G流量。
> > https://github.com/Jianyuann/docker-xray
> > ![image](https://user-images.githubusercontent.com/9197609/191013015-81bb577d-dfb9-4d90-8525-50d9466793e5.png)
> 
> 不知道为什么刚刚用了一会可以，后面就不行了，网页是能正常打开Bad Request，但是客户端io: read/write on closed pipe
> 
> 可能是需要矫正时间？

我最近试试，你可以先试试，看看mogenius 封不封 v2ray

**Comment by 8ty** [comment]
不封的好像

**Comment by 8ty** [comment]
感觉不是很可以，有时会莫名其妙的就停止运行

**Comment by zizifn** [comment]
我找到一个新的方式 https://deno.com/deploy。 code 是我自己写的，非常简单直白。 请看置顶issue，如果想试验，请联系我。近期会开repo的。还需要一点时间完善。。

**Comment by zizifn** [comment]
已经找到新的免费的，感觉不错。请查看，最新code..
