### ISSUE TITLE
cloudflare tunnel

### ISSUE THREAD

**Issue by Davendx** [zizifn/edgetunnel#53]
HI
in my region heroku address its not accessible(blocked by gov)
i tried with Zerotrust tunnel but receive same result the page doesnt load
revers proxy on "Workers.dev" seems work only without TLS 
what i can do to make it work

**Comment by zizifn** [comment]
Heroku will kill the free tier on November 28, 2022.

**Comment by zizifn** [comment]
cloudflare tunnel don;t need Workers.dev, please check https://github.com/zizifn/v2ray-heroku/blob/main/cloudflared-tunnel.md

**Comment by Davendx** [comment]
close

**Comment by zizifn** [comment]
heroku 已经不免费了，已经找到新的免费的，感觉不错。如果有需要，请查看，最新code..
