### ISSUE TITLE
免费的没了, 有没有其他推荐下?

### ISSUE THREAD

**Issue by Akise** [zizifn/edgetunnel#56]

**Comment by zizifn** [comment]
我或许可以 搞定 https://deno.com/deploy，但是这肯定不是v2ray 啦。我明天找时间试试把。。。所有的serverless 平台都不支持 request streaming， deno 支持。。我明天试试看。

**Comment by zizifn** [comment]
https://deno.com/deploy 已经试验成功。。。近期会开repo。

**Comment by zizifn** [comment]
请查看，最新code..
