### ISSUE TITLE
使用 vless 下的 main.ts 部署无法使用

### ISSUE THREAD

**Issue by Su-yj** [zizifn/edgetunnel#72]
使用 apps/deno-vless/src/main.ts 部署后，访问 deno 的项目地址，报以下错误：
```
request isn't trying to upgrade to websocket.
```
并且查看 deno 的日志发现报下面的错误：
```
[:0] request hadler has error TypeError: Stringified UUID is invalid
    at stringify (https://jspm.dev/npm:uuid@9.0.0:51:11)
    at WebSocket.socket.onmessage (file:///src/apps/deno-vless/src/main.ts:39:21)
    at WebSocket.wrappedHandler (deno:ext/web/02_event.js:1362:14)
    at innerInvokeEventListeners (deno:ext/web/02_event.js:755:9)
    at invokeEventListeners (deno:ext/web/02_event.js:795:7)
    at dispatch (deno:ext/web/02_event.js:664:11)
    at WebSocket.dispatchEvent (deno:ext/web/02_event.js:1043:14)
    at WebSocket.[[[eventLoop]]] (deno:ext/websocket/01_websocket.js:444:18)
```

**Comment by just4somefun** [comment]
我访问项目地址也是同样的提示，但实际已经部署成功了。

**Comment by zizifn** [comment]
已经部署成功，这个错误多数来源于dns请求的转发。由于edge 平台限制，目前不支持udp代理，但是应该不影响访问。。

**Comment by zizifn** [comment]
如何能提供，您访问什么网站时候，有这个错误的就更好了。

**Comment by zizifn** [comment]
> > 已经部署成功，这个错误多数来源于dns请求的转发。由于edge 平台限制，目前不支持udp代理，但是应该不影响访问。。
> 
> 所以项目部署成功后访问 done 的项目地址，返回这个`request isn't trying to upgrade to websocket.`是已经成功部署了吗？
> 
> > 如何能提供，您访问什么网站时候，有这个错误的就更好了。
> 
> 访问Google、GitHub都是，所有网站都打不开。 我不确定是不是v2ray的问题，但已经是按照你的步骤来配置的了。我换成项目里最新的releases后配置完，也是无法访问。

最新code兼容 v2ray 客户端，不需要下载 release里面的东西。具体配置，看readme里面的客户端配置。

**Comment by Su-yj** [comment]
在家里重新部署了一次，可以正常使用，不知道是不是跟公司网络有关系，明天再看一下

**Comment by Su-yj** [comment]
问题已解决，应该是我的 v2ray 客户端其他配置有问题，目前已经能用。
但还是发现几点问题，在浏览一些网站的时候，会报这样的错误，暂时不知道触发的条件
```
[www.google.com:443] socket errored: ErrorEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: WebSocket {
  url: undefined,
  readyState: 3,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
},
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: WebSocket {
  url: undefined,
  readyState: 3,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
},
  returnValue: true,
  timeStamp: 1670894262729,
  type: "error",
  message: "WebSocket protocol error: Connection reset without closing handshake",
  filename: "",
  lineno: 0,
  colno: 0,
  error: undefined
}

[youtube.com:443] socket errored: ErrorEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: WebSocket {
  url: undefined,
  readyState: 3,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
},
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: WebSocket {
  url: undefined,
  readyState: 3,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
},
  returnValue: true,
  timeStamp: 1670894254033,
  type: "error",
  message: "WebSocket protocol error: Connection reset without closing handshake",
  filename: "",
  lineno: 0,
  colno: 0,
  error: undefined
}
```

另外不确定是跟服务器有关，有时候打开 YouTube 会白屏，刷新依旧是白屏，但是如果我打开一下其他网站（如 Google）后，再打开 YouTube 就能正常访问

**Comment by zizifn** [comment]
> 问题已解决，应该是我的 v2ray 客户端其他配置有问题，目前已经能用。 但还是发现几点问题，在浏览一些网站的时候，会报这样的错误，暂时不知道触发的条件
> 
> ```
> [www.google.com:443] socket errored: ErrorEvent {
>   bubbles: false,
>   cancelable: false,
>   composed: false,
>   currentTarget: WebSocket {
>   url: undefined,
>   readyState: 3,
>   extensions: undefined,
>   protocol: null,
>   binaryType: undefined,
>   bufferedAmount: NaN
> },
>   defaultPrevented: false,
>   eventPhase: 2,
>   srcElement: null,
>   target: WebSocket {
>   url: undefined,
>   readyState: 3,
>   extensions: undefined,
>   protocol: null,
>   binaryType: undefined,
>   bufferedAmount: NaN
> },
>   returnValue: true,
>   timeStamp: 1670894262729,
>   type: "error",
>   message: "WebSocket protocol error: Connection reset without closing handshake",
>   filename: "",
>   lineno: 0,
>   colno: 0,
>   error: undefined
> }
> 
> [youtube.com:443] socket errored: ErrorEvent {
>   bubbles: false,
>   cancelable: false,
>   composed: false,
>   currentTarget: WebSocket {
>   url: undefined,
>   readyState: 3,
>   extensions: undefined,
>   protocol: null,
>   binaryType: undefined,
>   bufferedAmount: NaN
> },
>   defaultPrevented: false,
>   eventPhase: 2,
>   srcElement: null,
>   target: WebSocket {
>   url: undefined,
>   readyState: 3,
>   extensions: undefined,
>   protocol: null,
>   binaryType: undefined,
>   bufferedAmount: NaN
> },
>   returnValue: true,
>   timeStamp: 1670894254033,
>   type: "error",
>   message: "WebSocket protocol error: Connection reset without closing handshake",
>   filename: "",
>   lineno: 0,
>   colno: 0,
>   error: undefined
> }
> ```
> 
> 另外不确定是跟服务器有关，有时候打开 YouTube 会白屏，刷新依旧是白屏，但是如果我打开一下其他网站（如 Google）后，再打开 YouTube 就能正常访问

白屏可能和dns有关，尽量不太代理dns解析。选择ASIS。其他错误，如果能正常上网就忽略吧。

**Comment by dsas221203** [comment]
> 

怎么解决的

**Comment by zizifn** [comment]
maybe refer to issue https://github.com/zizifn/edgetunnel/issues/75#issuecomment-1354760119
