### ISSUE TITLE
两个域名

### ISSUE THREAD

**Issue by devfq** [zizifn/edgetunnel#74]
冒昧的问一下，有两个域名那个是hostname？

**Comment by zizifn** [comment]
哪两个?

**Comment by devfq** [comment]
一个是比较长的-——name-一串数字+deno.dev，一个是比较短的——name+deno.dev

**Comment by devfq** [comment]
![图片](https://user-images.githubusercontent.com/120479812/207482072-4848668b-33ba-4ed6-ae61-79c140d5bf78.png)

**Comment by zizifn** [comment]
> 一个是比较长的-——name-一串数字+deno.dev，一个是比较短的——name+deno.dev

都可以。我用短的。。

**Comment by devfq** [comment]
![图片](https://user-images.githubusercontent.com/120479812/207482418-d97817a9-37a0-4227-ac8c-fa2af62f5d16.png)
怎么说address的url跟tls的servername可以一样喽。

**Comment by zizifn** [comment]
> ![图片](https://user-images.githubusercontent.com/120479812/207482418-d97817a9-37a0-4227-ac8c-fa2af62f5d16.png) 怎么说address的url跟tls的servername可以一样喽。

是的。如果你不用CF 优选ip，tls server name 可以不用写。

**Comment by devfq** [comment]
好的，非常感谢
