### ISSUE TITLE
安卓端无法使用，请问如何排错

### ISSUE THREAD

**Issue by just4somefun** [zizifn/edgetunnel#75]
PC端使用v2rayN一切正常，同样的节点和配置在安卓上使用v2rayNG时app均无法使用，在手机浏览器上指定socks端口代理则正常，不知道什么原因。DNS策略均设置为ASIS

请教如何进行排错？

**Comment by zizifn** [comment]
大概率是DNS 设置问题，你需要尝试下。看看 安卓 v2rayNG 的各个DNS 设置，尝试下。

**Comment by zizifn** [comment]
> v2rayNG 电报app会有下面这样的报错，chrome浏览电报web版就没有 。 [91.108.56.165:443] request hadler has error TypeError: Stringified [91.108.56.165:443] request hadler has error BadResource: Bad resource ID

有错误没关系。手机电报可以正常使用吗？

**Comment by zizifn** [comment]
> > 电报可以加载信息，有些视频图片加载不了或速度慢 电报web加载信息视频图片就可以
> > v2rayNG 启用本地DNS，远程DNS用https://1.1.1.1/dns-query
 
这是我的设置。如何不还是不行，请多尝试下
![Uploading Screenshot_2022-12-16-20-13-33-039-edit_com.v2ray.ang.jpg…]()

**Comment by just4somefun** [comment]
> 大概率是DNS 设置问题，你需要尝试下。看看 安卓 v2rayNG 的各个DNS 设置，尝试下。

能修改设置的都尝试过了，包括：绕过局域网和大陆、全局、分应用代理、启用/关闭本地DNS，deno的节点就是不行，换成别的安卓客户端(trojan)，也是无法使用，但在PC客户端上畅行无阻。 

能分享一下你在安卓手机客户端的设置吗？

**Comment by zizifn** [comment]
> > 大概率是DNS 设置问题，你需要尝试下。看看 安卓 v2rayNG 的各个DNS 设置，尝试下。
> 
> 能修改设置的都尝试过了，包括：绕过局域网和大陆、全局、分应用代理、启用/关闭本地DNS，deno的节点就是不行，换成别的安卓客户端(trojan)，也是无法使用，但在PC客户端上畅行无阻。
> 
> 能分享一下你在安卓手机客户端的设置吗？

![Screenshot_2022-12-16-21-14-53-311-edit_com v2ray ang](https://user-images.githubusercontent.com/1803942/208106820-e456f311-0b8d-4681-ad10-f430c8bff279.jpg)

**Comment by just4somefun** [comment]
> > > 大概率是DNS 设置问题，你需要尝试下。看看 安卓 v2rayNG 的各个DNS 设置，尝试下。
> > 
> > 
> > 能修改设置的都尝试过了，包括：绕过局域网和大陆、全局、分应用代理、启用/关闭本地DNS，deno的节点就是不行，换成别的安卓客户端(trojan)，也是无法使用，但在PC客户端上畅行无阻。
> > 能分享一下你在安卓手机客户端的设置吗？
> 
> ![Screenshot_2022-12-16-21-14-53-311-edit_com v2ray ang](https://user-images.githubusercontent.com/1803942/208106820-e456f311-0b8d-4681-ad10-f430c8bff279.jpg)

感谢分享。 我最后尝试了把虚拟DNS的选项勾上，再重连一下节点，突然就正常了，再把虚拟DNS关掉，依然正常，也不懂究竟是否和这个有关系。

**Comment by zizifn** [comment]
> > > > 大概率是DNS 设置问题，你需要尝试下。看看 安卓 v2rayNG 的各个DNS 设置，尝试下。
> > > 
> > > 
> > > 能修改设置的都尝试过了，包括：绕过局域网和大陆、全局、分应用代理、启用/关闭本地DNS，deno的节点就是不行，换成别的安卓客户端(trojan)，也是无法使用，但在PC客户端上畅行无阻。
> > > 能分享一下你在安卓手机客户端的设置吗？
> > 
> > 
> > ![Screenshot_2022-12-16-21-14-53-311-edit_com v2ray ang](https://user-images.githubusercontent.com/1803942/208106820-e456f311-0b8d-4681-ad10-f430c8bff279.jpg)
> 
> 感谢分享。 我最后尝试了把虚拟DNS的选项勾上，再重连一下节点，突然就正常了，再把虚拟DNS关掉，依然正常，也不懂究竟是否和这个有关系。

可能有关系，就是目前deno 无法转发udp，然而有些客户端设置，dns请求会走代理。。
