### ISSUE TITLE
很棒的项目，给大佬点赞，不过有几个疑问

### ISSUE THREAD

**Issue by 8ty** [zizifn/edgetunnel#77]
1 youtube 打不开 ，打开是白屏
deno debug 日志：
![deno debug 日志](https://user-images.githubusercontent.com/92656899/208221766-0208d2e5-e33c-4fa3-ad87-7231c45a2239.png)

2 我看到官方doc里还讲到了有tw 和 hk 地区，是自动分配吗，可以自己指定吗？然后就很尴尬，宽带是sg，就很快，然后流量就变成us区了，不知道官方的分配是怎么样的
![地区](https://user-images.githubusercontent.com/92656899/208221824-c5e2b94e-2138-4a10-8a63-f2b3497fec62.png)

小小的建议：其实大佬你可以像其他协议（比如 navie 或者 hysteria ）一样写一个内核如何借助v2rayn来分流的，不需要用js来实现vless,这样只能支持更好一点

**Comment by zizifn** [comment]
> 1 youtube 打不开 ，打开是白屏 deno debug 日志： ![deno debug 日志](https://user-images.githubusercontent.com/92656899/208221766-0208d2e5-e33c-4fa3-ad87-7231c45a2239.png)
> 
> 2 我看到官方doc里还讲到了有tw 和 hk 地区，是自动分配吗，可以自己指定吗？然后就很尴尬，宽带是sg，就很快，然后流量就变成us区了，不知道官方的分配是怎么样的 ![地区](https://user-images.githubusercontent.com/92656899/208221824-c5e2b94e-2138-4a10-8a63-f2b3497fec62.png)
> 
> 小小的建议：其实大佬你可以像其他协议（比如 navie 或者 hysteria ）一样写一个内核如何借助v2rayn来分流的，不需要用js来实现vless,这样只能支持更好一点

youtube 打不开，我感觉是DNS 问题，也不排除是code bug, 目前发现一些问题，我还没有来得急修复。
deno 是edge function， 你的code 在每个数据中心都有，deno自己选择，我分别在 中国访问deno，和美国的机器上访问deno，他们的ip都是一个，但是会被路由到不同的数据中心。。我不是很清楚deno 怎么做路由的。
