### ISSUE TITLE
UDP(DNS) support

### ISSUE THREAD

**Issue by zizifn** [zizifn/edgetunnel#79]
due to deno deploy limitation, UDP support is not doable currently. But deno has UDP support in their roadmap.. 

This impacts DNS proxy...

https://deno.com/deploy/docs/runtime-api#future-support

**Comment by Fangliding** [comment]
目前可以用dot/doh 这俩是用tcp的。以前tuic一个版本有bug不能转发udp我就这么搞的()

**Comment by zizifn** [comment]
node-vless UDP 已经完成。

**Comment by zizifn** [comment]
use dns over tcp in server will solve DNS proxy with UDP enable..
