### ISSUE TITLE
deta.sh 这个平台好像也可以部署js，可以尝试一下

### ISSUE THREAD

**Issue by 8ty** [zizifn/edgetunnel#80]
不过不知道能不能实现

**Comment by zizifn** [comment]
> 不过不知道能不能实现

不支持websocket 不可以，当然如果支持 http request streaming，也是可以的。有时间再试试吧。另外deno 蛮好的，在可预见的未来，cf worker 也可以直接部署本项目。。。基本不需要其他平台。

**Comment by yuchen3000** [comment]
应该不行的。
Websockets and long-running processes do not work on Micros. (examples: socket.io or Discord bots won't work).

**Comment by yuchen3000** [comment]
> > 不过不知道能不能实现
> 
> 不支持websocket 不可以，当然如果支持 http request streaming，也是可以的。有时间再试试吧。另外deno 蛮好的，在可预见的未来，cf worker 也可以直接部署本项目。。。基本不需要其他平台。

glitch和netlify可以吗？我看了下，这个项目目前好像只能Deno部署，代码里还从Deno导入了一些东西，所以要移植到其他平台还得改改才行

**Comment by zizifn** [comment]
> 

glitch 应该可以， netlify 和 vercel 目前都不可以，我现在由于众所周知的疾病，身体没有完全恢复，等恢复后写个 faq 解释下为什么有些平台可以，有些不可以。

**Comment by zizifn** [comment]
更新了文档，解释了，怎么判断哪些平台支持。。。
https://github.com/zizifn/edgetunnel#%E9%82%A3%E4%BA%9B%E5%B9%B3%E5%8F%B0%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8
