### ISSUE TITLE
提示要账号和密码！

### ISSUE THREAD

**Issue by bujieshi** [zizifn/edgetunnel#82]
我这里部署完成后！点击view后，跳转到网址，然后提示要账号和密码，但是我没有找到账号和密码在哪里？请大佬帮忙看看！第一次玩，谢谢大佬！

**Comment by zizifn** [comment]
看文档哦。把uuid放进去就可以。

**Comment by bujieshi** [comment]
> 

好吧，不好意思，没有仔细看文档！
