### ISSUE TITLE
日志错误，不知道是不是bug

### ISSUE THREAD

**Issue by KENAN1412** [zizifn/edgetunnel#84]
![图片](https://user-images.githubusercontent.com/77651819/209453580-55593d94-7603-4ce0-8f4c-18bfd993073c.png)

**Comment by zizifn** [comment]
应该是，只不过我暂时该不了，过几天吧，恢复身体。

**Comment by zizifn** [comment]
> 应该是，只不过我暂时该不了，过几天吧，恢复身体。

同步下代码吧，错误大幅度减少。

**Comment by KENAN1412** [comment]
刚刚同步代码，一开始好好的。后来就不行了，代理一直报连接失败。
![图片](https://user-images.githubusercontent.com/77651819/212435541-d08c033c-8f35-4d66-bc70-1dc51ddedaea.png)

**Comment by KENAN1412** [comment]
不知道是不是被封了

**Comment by zizifn** [comment]
> 不知道是不是被封了

只要 你的 deno URL 能访问就没有封。

**Comment by alexsunlee** [comment]
我也有错误

[16-courier.push.apple.com:443--0.2708725149263598] remoteConnection!.readable is close
2023-03-23 14:20:02
[youtubei.googleapis.com:443--0.727826016567745] processWebSocket has exception  can't accept data from remoteConnection!.readable when client webSocket is close early
2023-03-23 14:19:18
[youtubei.googleapis.com:443--0.727826016567745] readableWebSocketStream pipeto has exception ErrorEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  srcElement: null,
  target: WebSocket {
  url: undefined,
  readyState: 3,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
},
  returnValue: true,
  timeStamp: 1679581158508,
  type: "error",
  message: "WebSocket protocol error: Connection reset without closing handshake",
  filename: "",
  lineno: 0,
  colno: 0,
  error: undefined
}

**Comment by alexsunlee** [comment]
deno用不了，render不影响使用

**Comment by alexsunlee** [comment]
> > deno用不了，render不影响使用
> 
> 怎么用不了? 详细点。你的 deno 项目可以访问吗？

刚部署完的时候确实用不了，今天重新试了试又能用了。。。
