### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by momo54181** [zizifn/edgetunnel#90]
503 Service Unavailable
The requested deployment is currently suspended.

code: DEPLOYMENT_SUSPENDED

**Comment by momo54181** [comment]
搞个账号继续飞

**Comment by bujieshi** [comment]
哈哈哈，我的也变成503了

**Comment by redstoneleo** [comment]
我的也
`500-The user is currently suspended. If you believe this has occurred in error please contact deploy@deno.com.`

**Comment by zizifn** [comment]
> 我的也 `500-The user is currently suspended. If you believe this has occurred in error please contact deploy@deno.com.`

我无法给出建议，项目一开始提示了风险。如果你愿意可以风险你的使用量吗？

**Comment by zizifn** [comment]
> 感觉是被封号了，什么都看不到
> 
> ![image](https://user-images.githubusercontent.com/5896180/227208798-f8667c61-e30e-43c7-9662-21f4048395ff.png)

自我感觉下呢，看下客户端的流量使用情况。

**Comment by redstoneleo** [comment]
用不了就被我之前删除了，所以看不到了，反正应该也没用多少。现在被封号了

**Comment by zizifn** [comment]
close as deno is dead, please wait for cf worker...
