### ISSUE TITLE
在deno部署完，点击view打开401页面后，找不到在哪输入UUID进行验证

### ISSUE THREAD

**Issue by purepoorx** [zizifn/edgetunnel#92]
在deno部署后，打开Not set valid UUID in Environment Variables.的401页面后，没有在页面上看到在哪可以输入UUID进行验证，求指点迷津，谢谢了

**Comment by purepoorx** [comment]
以为是浏览器的问题，有可能脚本被禁用了，换了几个浏览器，也是没找到在哪输入UUID进行验证

**Comment by zizifn** [comment]
> 以为是浏览器的问题，有可能脚本被禁用了，换了几个浏览器，也是没找到在哪输入UUID进行验证

看文档，这个是在 deno 管理界面设置。
