### ISSUE TITLE
【调研】cloudfalre grpc

### ISSUE THREAD

**Issue by zizifn** [zizifn/edgetunnel#97]
cloudfalre 目前只能 proxy grpc。暂时还不能拦截grpc.....即使可以，也需要相关人开发 grpc worker 版本。。

**Comment by KENAN1412** [comment]
是可以部署在cloudflare的worker上吗？

**Comment by zizifn** [comment]
> 是可以部署在cloudflare的worker上吗？

cloudflare worker  目前无法 grpc，但是部署到 cloudflare 有点希望。具体细节讨论你可以加入 tg
