### ISSUE TITLE
有人愿意接手这个项目吗？

### ISSUE THREAD

**Issue by zizifn** [zizifn/edgetunnel#98]
略感到一些风险，有人愿意接受这个项目吗？我还是可以继续开发。

**Comment by future13800** [comment]
> 略感觉到一些风险，有人愿意接受这个项目吗？我还是可以继续开发的。

有何风险？

**Comment by zizifn** [comment]
> > 略感觉到一些风险，有人愿意接受这个项目吗？我还是可以继续开发的。
> 
> 有何风险？

潜在被喝茶风险，主要有心人真的可以根据我的 GitHub 账户，从而找到我。

**Comment by Misaka-blog** [comment]
> 略感到一些风险，有人愿意接受这个项目吗？我还是可以继续开发。

联系我tg @misakablog2

**Comment by Fangliding** [comment]
开一个小号专门来commit git可以对单仓库修改git config 就可以用小号进行commit不影响大号其他正常开发 不过合并pr和回复issues也得开小号

**Comment by fscarmen** [comment]
> 略感到一些风险，有人愿意接受这个项目吗？我还是可以继续开发。

开小号玩不行吗？

**Comment by daiaji** [comment]
注意安全
